### ISSUE TITLE
How to render both sidebar and dialog?

### ISSUE THREAD

**Issue by piavgh** [enuchi/React-Google-Apps-Script#10]
In your example, React app renders a dialog.

I customized code and I can render a Sidebar in Forms addon.

My question is how to render both a dialog and a sidebar?

For example, in Forms Menu, I have 2 items: Get started and About

If I click Get started, the sidebar will be displayed

If I click About, the dialog will be displayed.

At the moment I can't find any way so that React app renders both .html files (sidebar.html and about.html) because React is SPA so there is only one entry point.

Thank you.

**Comment by piavgh** [comment]
I figured it out, basically I need to add another entry point for About page

Add in `webpack.config.js`:

```
const html2Plugin = new HtmlWebpackPlugin({
  template: "./src/client/about-template.html",
  filename: "about.html",
  inlineSource: '.(js|css)$' // embed all javascript and css inline
});
```

```
const aboutConfig = Object.assign({}, sharedConfigSettings, {
  name: "CLIENT",
  entry: "./src/client/aboutPage.jsx",
  output: {
    path: path.resolve(__dirname, destination)
  },
  resolve: {
    extensions: ['.js', '.jsx', '.json']
  },
  module: {
    rules: [
      // eslintConfig,
      {
        test: /\.jsx$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader"
        }
      },
      {
        test: /\.css$/,
        use: [ 'style-loader', 'css-loader' ]
      }
    ],
  },
  plugins: [
    html2Plugin,
    new HtmlWebpackInlineSourcePlugin()
  ]
});
```

```
module.exports = [
  appsscriptConfig,
  clientConfig,
  serverConfig,
  aboutConfig,
];
```

**Comment by enuchi** [comment]
#17 now adds support for multiple dialogs/sidebars, based on your code above. See the updated Readme on how to set this up: https://github.com/enuchi/React-Google-Apps-Script#multiple-dialogs
