### ISSUE TITLE
There was an error during the transport or processing of this request. Error code = 10, Path = /wardeninit

### ISSUE THREAD

**Issue by tsdexter** [enuchi/React-Google-Apps-Script#109]
Right in the middle of a hot reload development session the app started crashing in the modal/dialog popup with the error below.

It won't render the app anymore. If I run `npm run deploy` the app works, but the live reloading/`npm start` is now getting this error. Any ideas? 

```
{
    "message": "There was an error during the transport or processing of this request. Error code = 10, Path = /wardeninit",
    "name": "TransportError"
}
crbug/1173575, non-JS module files deprecated.
```

**Comment by tsdexter** [comment]
Looks like I may have fixed it by loading the page in the modal (`https://localhost:3000/gas/web-app-impl.html`) in a new tab and then going to Advanced and 'proceed anyway'

**Comment by enuchi** [comment]
Check out the section in the Readme @tsdexter to set up your https cert locally, so you don't have to do the Advanced -> proceed process.

https://github.com/enuchi/React-Google-Apps-Script#-new-local-development-

**Comment by tsdexter** [comment]
@enuchi  I did do that process and it was working great for some time, then right in the middle of development it suddenly stopped working from one save to the next, until I did the 'proceed anyway'.
