### ISSUE TITLE
How to make a Google Apps Script standalone web app with this project?

### ISSUE THREAD

**Issue by MikeWarren2014** [enuchi/React-Google-Apps-Script#110]
Thanks so much for creating this amazing project! For a while, since I learned React (and MobX), I've been wanting to use it inside Google Apps Script projects!

That being said, I have a freelancing client who is looking for a UI that can interact with her Google Sheets, to which the most reasonable approach would be to create a web app. I've created Google Apps Script based web apps in the past, in fact it was my very first exposure to it. [It seems like they only support raw HTML templates and jQuery](https://developers.google.com/apps-script/guides/web) .

However, knowing all that I know now, I'd like to create a simple React + MobX MVVM-based web app on the Google Apps Script. How can we use this project to get that done?

**Comment by MikeWarren2014** [comment]
UPDATE: I should have read more carefully! This is embarassing!!

From looking at [`src/server/ui.js`](https://github.com/enuchi/React-Google-Apps-Script/blob/master/src/server/ui.js), I see that is how the main use case, injecting React project into the modals in Google Apps Script projects that control Google Spreadsheets, even gets to happen.

We could customize this and make this more general, by editing out the `onOpen` method. I see it is developer's responsibility to do that :P

Great project! It's easy to follow, and I can see how I can make this my own, with MobX and MVVM!

**Comment by axeligl** [comment]
Hey, I'm trying to do the same thing. Could you do it?

**Comment by axeligl** [comment]
Never mind, I think I found it.
You have to include a doGet() function on src/server/ui.js so you can deploy as WebApp on GAS.
Also, include it on src/server/index.js

Then following the documentation I understand the rest.

**Comment by axeligl** [comment]
Thanks for the advice. Also, nice work!
