### ISSUE TITLE
Dev mode not loading content 

### ISSUE THREAD

**Issue by MK-Mike** [enuchi/React-Google-Apps-Script#113]
Thanks @enuchi for creating this awesome tool. 

Not really a problem per se, but thought other might find this useful. 

I followed all the instructions, and got this working if I deployed it, however the dev mode wasn't working for me. The modal window appeared but no content was loaded in the iframe. 

I eventually figured out that this was due to add / script blocking by my browser (Brave) and turning that off fixed the problem (in my case setting Brave "shields" to down). 

It might be worth including a line in the readme instructions on dev mode in case others run in to a similar problem with add blockers / privacy extensions. 

Thanks again for creating this tool.

**Comment by enuchi** [comment]
Hi @MK-Mike, thanks for the tip. Feel free to open a PR adding a sentence to the Readme.
