### ISSUE TITLE
Drag and Drop component into doc

### ISSUE THREAD

**Issue by dostoievsky** [enuchi/React-Google-Apps-Script#114]
I need do an Add-on to automate the creation and sending of documents on my company.

We can do that with macros and csv using the docs ecosystem, but we get things like {{variable}} on document.

So if we are sending a document to people over a csv,

in docs, it appears like

"Hello {{name}}!"

Well, I was looking at this realy cool booilerplate and I would like to know if its possible I get thoose variables, like name, email, mapped as buttons on my sidebar add-on, and then, click on that button and drag it on document, so it would not appear like {{name}} but a component box "name".

With that people will not clear {{variables}} because their look and feel.

**Comment by dostoievsky** [comment]
I'll close that issue because its not possible create those dom components and make then interact with the dom of docs or things like that.

**Comment by enuchi** [comment]
Hi @dostoievsky, yes that's right. You can't interact with the main doc or sheet from a sidebar add-on in the way you're describing. This is the one of the limitations of Google add-ons.
