### ISSUE TITLE
Problem when using Clasp 2.4.0 with Node v16.14.0

### ISSUE THREAD

**Issue by spjanic10** [enuchi/React-Google-Apps-Script#118]
I had a problem with the following error:

✖ script.google.com 
✖ Error: Looks like you are offline.

I was able to fix it by switching the Clasp version back to 2.3.1.

**Comment by enuchi** [comment]
Hmm thanks for pointing out. Looks like possibly same issue reported at clasp repo: https://github.com/google/clasp/issues/872. May need to pin to 2.3.1.

**Comment by enuchi** [comment]
I saw the same issue at times in CI pipeline. Right now updated to pin clasp version to 2.3.1 but will investigate if future versions of clasp fix this issue. Thanks for pointing out.
