### ISSUE TITLE
Upgrade to Babel v7?

### ISSUE THREAD

**Issue by piavgh** [enuchi/React-Google-Apps-Script#12]
Hi @enuchi ,

Do you have the plan to update this project using Babel v7?

There is something that I want to try, for example, `public class field syntax`, and it somehow requires v7 https://babeljs.io/docs/en/babel-plugin-proposal-class-properties

If you do, can you please tell me when will it be released?

Thank you very much.

**Comment by enuchi** [comment]
Happy to review if you want to open a PR!

**Comment by piavgh** [comment]
Thanks, please check this PR when you have time https://github.com/enuchi/React-Google-Apps-Script/pull/13

**Comment by enuchi** [comment]
Great, thanks, will review this soon!

**Comment by enuchi** [comment]
Merged in #13 which should includes Babel v7 and should support public class field syntax.
