### ISSUE TITLE
Local dev server for web app

### ISSUE THREAD

**Issue by phillpeters** [enuchi/React-Google-Apps-Script#125]
Like many before me, I first want to say what an amazing project this is.  Thanks for taking the time to create this.  I've been wanting to do some serious apps script development but dreaded the idea of doing it in the web editor.  A google search for React with Google Apps Script brought me here and I've already managed to modify the project to spin up a web app that is live in the dev server.

Just a few quick questions.  Navigating to localhost:3000 after starting the dev server takes me to a page that lists the project files.  I had to navigate to /dist/webapp.html to see the actual app.  Is there a way I can point the "Project is running at..." url to this path?

Also, as a webapp, I am not using the UI functions, but I'll quite likely end up using the server functions.  In any case I'd like to keep these files for reference.  Is there any reason not to keep them?

**Comment by enuchi** [comment]
Hi @phillpeters, thanks for the kind note.

Not sure exactly how you've set things up but search for webapp in this repo. You'll see some closed issues where others have described their webapp setups in case it's helpful.

See https://webpack.js.org/configuration/dev-server/#devserveropen for modifying the default open page when launching webpack dev server. Is that what you are looking for? Note that server functions won't work in local development when using webapps -- server functions will only work in development when developing inside dialogs as in the sample.

I'd just remove the imports and exports of the UI functions you don't need from src/server/index.ts and they won't get included in your app or exposed publicly. You can then still keep the files around if they're helpful.

**Comment by phillpeters** [comment]
This is very helpful, thank you!  The webpack docs page you linked seems to be for a newer version of webpack though.  In order to set the opening page, it says to add the `open` property to the `devServer` object with a path:
```
devServer: {
  open: ['/my-page']
}
```
This wasn't working for me, so a quick bit of googling showed that an older version of webpack has a different config:
```
devServer: {
  open: true,
  openPage: 'my-page'
}
```

It's a bit disappointing to learn that I can't use server functions in local dev with webapps, although it makes sense.  Your solution here is so precisely what I need for a current project.  Do you know of any workarounds?  Could I make a dialog window the size of the viewport and just copy my code to a wepapp project when complete?

I appreciate the support!

**Comment by enuchi** [comment]
Yes that should work. I think webapps behave slightly differently than regular dialogs in a couple places so you may have to account for those differences -- user context, browser history, maybe something else. But overall should work the same.
