### ISSUE TITLE
support for import() ?

### ISSUE THREAD

**Issue by jchnxu** [enuchi/React-Google-Apps-Script#128]
When I tried using the asynchronous import, heres what I got in the console

<img width="789" alt="image" src="https://user-images.githubusercontent.com/4531670/171029416-2cb3c0a2-4396-4a92-8f3a-15fd2629035e.png">

And I can only see code.gs in the online editor
<img width="228" alt="image" src="https://user-images.githubusercontent.com/4531670/171029783-57564049-3457-4a31-964d-301dd4121273.png">

**Comment by enuchi** [comment]
Can you share the snippet where you are importing? It shouldn't be creating those 0.main.js files -- did you change any configuration?

**Comment by enuchi** [comment]
@jchnxu looking into this a bit more and don't believe dynamic importing will provide any benefit with this repo. Google Apps Scripts doesn't allow loading separate chunks -- it just loads a single html file at a time. The approach with this repo is to load all scripts inline into a single html file. This makes initial load time slower, but that is what is possible given the Google Apps Script environment. If you have any ideas on how to support dynamic imports I'm happy to hear them.
