### ISSUE TITLE
Windows Live react issue

### ISSUE THREAD

**Issue by Deosaju** [enuchi/React-Google-Apps-Script#132]
$ npm run setup:https

> react-google-apps-script@2.1.0 setup:https
> mkdirp certs && mkcert -key-file ./certs/key.pem -cert-file ./certs/cert.pem localhost 127.0.0.1

The filename, directory name, or volume label syntax is incorrect.

Deo Saju@DESKTOP-742C9KU MINGW64 ~/Downloads/Bulk-image-upload-GAS (main)
$ npm run setup:https

> react-google-apps-script@2.1.0 setup:https
> mkdirp certs && mkcert -key-file ./certs/key.pem -cert-file ./certs/cert.pem localhost 127.0.0.1

The filename, directory name, or volume label syntax is incorrect.

**Comment by Deosaju** [comment]
https://172.16.22.187:3000/'

servering at local host but showing 
Cannot GET /
error

**Comment by enuchi** [comment]
Can you share the error you are seeing? Also looks like you are not loading app on same ip you are creating cert for.

**Comment by Deosaju** [comment]
Issue was solved , I was using brave browser , That caused the issue of certificate verification
