### ISSUE TITLE
How to create a calendar addon using this template 

### ISSUE THREAD

**Issue by omridevk** [enuchi/React-Google-Apps-Script#140]
Great starter project.
I am not sure how to use this template to create a Sidebar addon to google calendar, any help will be much appreciated.
Thanks

**Comment by enuchi** [comment]
Hey there, this project is used for running a react app inside sidebars/dialogs. As far as I know sidebars/dialogs are only supported in Google Docs, Forms, Slides, and Sheets: https://developers.google.com/apps-script/guides/dialogs#custom_dialogs.
