### ISSUE TITLE
remove babel-eslint package

### ISSUE THREAD

**Issue by RealSlimMahdi** [enuchi/React-Google-Apps-Script#143]
Hi @enuchi ,

Thanks for the last update; very nice.
Should you not consider removing the babel-eslint package, especially now that you added @babel/eslint-parser ?

Cheers,

**Comment by enuchi** [comment]
Yes I think this was related to #124 , right? `babel-eslint` probably should have been removed there. Is this what you're referring to?

**Comment by enuchi** [comment]
Removed
