### ISSUE TITLE
"Built With" section?

### ISSUE THREAD

**Issue by leonardolombardi07** [enuchi/React-Google-Apps-Script#144]
Hi Enuchi!

Thanks again for creating this wonderful boilerplate. With it I built my first add-on, **Caption Manager** I'm very happy. Thank you.

The add-on is available on the [Google Marketplace](https://workspace.google.com/marketplace/app/caption_manager/50320676631) and the code can be seen at [https://github.com/Caption-Manager/caption-manager](https://github.com/Caption-Manager/caption-manager).

I would like to publicize my add-on, to receive more feedback from users and software developers. Some I'm trying to do some marketing...

With that in mind, what do you think about creating a **"Built with"** section in the README, similar to the one that exists in the [Semantic UI React repository](https://github.com/Semantic-Org/Semantic-UI-React#built-with)? This way the add-on could be seen by more people and at the same time it would promote your boilerplate 😃.

Don't know, it's just an idea. 
Again, thanks!

**Comment by enuchi** [comment]
Hi @leonardolombardi07 , probably at the moment I won't add this since there isn't a critical mass and it would just be one add-on. Maybe if a few others ask... 😄 

Congrats on publishing your add-on though!
