### ISSUE TITLE
Does this repo work with app script as a standalone app (not using Sheets)?

### ISSUE THREAD

**Issue by thiZguy** [enuchi/React-Google-Apps-Script#15]
I've cloned this project looking forward to use it as a AppsScript standalone app, but the repo's setup explains how to start with Sheets... I´ve tried using my AppsScript app's id but when I "run" the project it won't work:

![image](https://user-images.githubusercontent.com/18606056/61137983-98f7c300-a494-11e9-9181-45c2752c956d.png)

> Missing ; before statement. (line 5810, file"main")

I didn't install anything yet, using just a fresh clone of the project.

Maybe I'm expecting a feature? what i'm trying is even possible?

**Comment by enuchi** [comment]
You can actually delete the `main` file as it's not needed. If you push the files using `clasp` then that file won't be included (see the `.claspignore` file). If you've copied them manually then just skip that file.

**Comment by enuchi** [comment]
Also if you run this as a standalone script, make sure to update the `onOpen` and `openDialog` functions in `sheet-utilities.js`, since `SpreadsheetApp.getUi()` only works in a script that is bound to a spreadsheet.

**Comment by enuchi** [comment]
#16 now removes the `main.js` file from `./dist` after build

**Comment by thiZguy** [comment]
Thanks it work with the new merge and editing sheet-utilities.js creating a doGet function ;-)
