### ISSUE TITLE
React hot reload on local dev server

### ISSUE THREAD

**Issue by Raj00377** [enuchi/React-Google-Apps-Script#150]
Hi,

While running on local machine using `npm run start` , Any changes in routes doesn't hot reload the page i need to re-run the command `npm run start` and close the sheet to reflect that change.

Also, I'm getting this warning `<w> [ReactRefreshPlugin] Hot Module Replacement (HMR) is not enabled! React Refresh requires HMR to function properly`. I have followed all the steps present in readme.md

![Screenshot from 2022-10-31 13-04-50](https://user-images.githubusercontent.com/40709274/198955785-1ec73d65-ea04-413a-a0c5-a1ba6dca9fc0.png)

**Comment by apugoneappu** [comment]
Facing the same issue, @enuchi any help?

**Comment by enuchi** [comment]
You can ignore the warning. Should be working despite what it says.

Can you confirm it doesn't work for you with a fresh clone? Also not sure what is meant by changes in route as there is only one route per page.

**Comment by apugoneappu** [comment]
Can confirm it's working 👍

**Comment by Raj00377** [comment]
> You can ignore the warning. Should be working despite what it says.
> 
> Can you confirm it doesn't work for you with a fresh clone? Also not sure what is meant by changes in route as there is only one route per page.

Changes in route means, if i add a new route/ new page i need to re-run the command `npm run` start

**Comment by enuchi** [comment]
Yes if you add a new client entrypoint and add the config to the webpack.config.js file you will need to restart `npm run start`.
