### ISSUE TITLE
Out of the box version of this for Google Docs

### ISSUE THREAD

**Issue by josh-may** [enuchi/React-Google-Apps-Script#152]
Thanks for building this cathedral Elisha! I'm learning a lot going through it 🙏

One recommendation - It would be nice to have an out of the box version of this for Google Docs. I'm in the process of migrating it over but it's a battle. 

Thanks again,
Josh

**Comment by enuchi** [comment]
Thanks Josh, appreciate it. Will consider adding in the future but no promises. On the plus side, you will understand how it all works when you're done migrating it 😄

**Comment by josh-may** [comment]
@enuchi boom done - https://github.com/josh-may/react-app-script-g-documents :)

**Comment by enuchi** [comment]
Nice work @josh-may! Gonna close this then.
