### ISSUE TITLE
[Q] Set the new OAuth 2.0 Client ID to the project. 

### ISSUE THREAD

**Issue by Raj00377** [enuchi/React-Google-Apps-Script#166]
Hi, I've mistakently deleted existing OAuth 2.0 Client ID in google cloud console which was used in the project. Now i've created a new one, but still the project points to the exising OAuth 2.0 Client ID , Can anyone explain how to set the new OAuth 2.0 Client ID to the existing project. 

Screenshot for the error:

![Screenshot from 2023-01-05 16-55-05](https://user-images.githubusercontent.com/40709274/210769609-bd225223-b0af-434c-b948-344cb4ca9168.png)

**Comment by enuchi** [comment]
Please check google documentation or open a ticket in the respective repo.
