### ISSUE TITLE
Cannot deploy app-script

### ISSUE THREAD

**Issue by tomzacchia** [enuchi/React-Google-Apps-Script#168]
I cloned the project and ran into the following problem when running `npm run deploy`

`
Cannot find package '.../app-script/node_modules/ts2gas/' imported from .../app-script/node_modules/@google/clasp/build/src/files.js
`

There are three separate commands being run by the deploy script. `rimraf dist && npm run build` works without any issue, `npx clasp push` is the script that is producing the error above. 

Has anyone experienced this? @enuchi

**Comment by enuchi** [comment]
Hmm. Did you try asking in google/clasp? Can you try running that project on its own and see if you run into same issues when running clasp push?

Also curious what OS and node version you're using.

**Comment by tomzacchia** [comment]
I'll ask in google clasp. What do you mean by "on its own?" 

OS: Mac OS 12.3.1
Node: v16.13.1

**Comment by tomzacchia** [comment]
@enuchi silly me, i had the rootDir path in `.clasp.json` because I've been playing with multiple app-script templates and copy-pasta'ed my way to frustration.

**Comment by enuchi** [comment]
Sounds good @tomzacchia
