### ISSUE TITLE
Parsing error: Unexpected reserved word 'interface'. 

### ISSUE THREAD

**Issue by saadbahir** [enuchi/React-Google-Apps-Script#177]
I am running in this eslint errors in the typescript files with an interface

`Parsing error: Unexpected reserved word 'interface'. `

```
interface FormInputProps {
  submitNewSheet: (sheetName: string) => {
    name: string;
    index: number;
    isActive: boolean;
  };
}
```

Has anyone encountered a similar error?

**Comment by enuchi** [comment]
Not sure as it works for me with my setup. Maybe you can share which code editor and OS you're using?

Also does it happen for you with a fresh clone and install of this repo?

**Comment by saadbahir** [comment]
thanks @enuchi  for your answer!
I am using VScode with MacOS Big Sur v11 

This indeed happens with a fresh clone and install of this repo

**Comment by saadbahir** [comment]
@enuchi I fixed it by replacing 

`"parser": "@babel/eslint-parser"`

by

`"parser": "@typescript-eslint/parser"`

in the file `/src/client/.eslintrc.json`
