### ISSUE TITLE
Cannot read properties of undefined (reading 'Routes')  

### ISSUE THREAD

**Issue by dhn205** [enuchi/React-Google-Apps-Script#189]
I'm new and I'm facing this issue. Development mode worked fine, but deploy did not
![image](https://user-images.githubusercontent.com/112550579/235470911-268c6c46-9a9a-4953-8b0d-ea2937b4e52c.png)
Link in index.tsx is: https://unpkg.com/react-router-dom@6.11.0/index.tsx

**Comment by enuchi** [comment]
Please search for various issues raised here with react router dom

**Comment by dhn205** [comment]
I solved the issue from #34
