### ISSUE TITLE
Styled Components issue

### ISSUE THREAD

**Issue by macabacus-ra** [enuchi/React-Google-Apps-Script#192]
Hello, I have used styled components with this project that I started in March and I know it works well. However, I recently started a new project, so I started everything from scratch again, and now styled-components are not working. I keep getting an error when running "npm install"
I have tried many different things like: styled-components@latest , styled-components@5, and e few others and nothing works.

**Comment by enuchi** [comment]
Can you share the error? If you are getting the error while running `npm install` then I think it is some issue outside of this project.
