### ISSUE TITLE
Can only add menu to 1 type of doc/slides/sheet ... ?

### ISSUE THREAD

**Issue by sunshineo** [enuchi/React-Google-Apps-Script#197]
I tried to have onOpen be like
```javascript
export const onOpen = () => {
  try {
    const menu = DocumentApp.getUi()
      .createMenu('doc menu')
      .addItem('doc item', 'docFuction')

    menu.addToUi();
  }
  catch (e) {
  }

  try {
    const slidesMenu = SlidesApp.getUi()
      .createMenu('slides menu')
      .addItem('slides item', 'slidesFuction')

    slidesMenu.addToUi();
  }
  catch (e) {
  }
};
```
But this only worked for doc not slides. If I reverse the order, then it works for slides not doc.
Can my app for both doc and slides?

**Comment by enuchi** [comment]
Not sure. I'd be surprised if it worked. Are you trying to have the same code work for both?

Does it throw an error, or in other words can you print `e`?

**Comment by sunshineo** [comment]
Yes, we want our add on to add menu to both Doc and Slides. (They also pretty much do the same thing of get some content and insert)
And today I'm seeing this code is just working. I'm not sure if I saw it wrong yesterday or I'm seeing things now. Will report back. Thanks!

**Comment by enuchi** [comment]
OK sounds good. Let me know if resolved.

**Comment by sunshineo** [comment]
It's working. Thank you!
