### ISSUE TITLE
Error When Loading Page in Local Development - "Cannot GET /"

### ISSUE THREAD

**Issue by amadeuscode10** [enuchi/React-Google-Apps-Script#198]
Hello, 

Thank you for this project. It's exactly what I'm looking for. I was able to install everything and I can deploy to the spreadsheet directly with no problem. However, I am having issues with local development part of it. 

I was able to install the certificates and I get no errors running `npm start` . When I access https://localhost:3000/ , the page is loaded with the following message: Cannot GET /

I have checked the console log in the browser and the following messages are outputted :
`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). [prepareInjection.js:249:78](moz-extension://ee0dd021-f8b2-4b23-95a4-a249a354eb66/build/prepareInjection.js)`
`Content Security Policy: The page’s settings blocked the loading of a resource at https://localhost:3000/favicon.ico (“default-src”). ```
[FaviconLoader.jsm:180:19](resource:///modules/FaviconLoader.jsm)`
`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).`

I have made no modifications to the project and I am running it as is from the template. 

I have attempted to access the site from Firefox and Chrome. I have disabled any add on and removed any enhanced securities (site protection, ad blocker ect) from the browsers. I am running on Linux (Pop Os!). 

Any suggestions on how to approach the problem?

**Comment by enuchi** [comment]
What happens when you try to open the add on from the spreadsheet after running `npm start`?

**Comment by amadeuscode10** [comment]
> 

The add on works perfectly fine in the spreadsheet directly after running npm start. I can make changes and deploy them, and they will be reflected on the spreadsheet. 
![Screenshot from 2023-08-05 15-24-58](https://github.com/enuchi/React-Google-Apps-Script/assets/66760942/0f28e4ba-a788-4ffb-948a-476dcf6b7341)

However, running `npm start` and going to https://localhost:3000/
I see the following
![Screenshot from 2023-08-05 15-28-34](https://github.com/enuchi/React-Google-Apps-Script/assets/66760942/bc53b9e7-fb4d-4293-827c-16ac4cbf1b06)

**Comment by enuchi** [comment]
So it looks like everything's running correctly. When you run `npm start` it deploys a shell that runs the react app in development mode, but inside the spreadsheet add on. Try running `npm start` and then change the MUI file (for example change the text in the header that says "MUI demo!") and save the file. The change should immediately be reflected inside the add on window within the spreadsheet. No need to redeploy. 

This project is designed to allow you to run server functions while developing your react app, but you need to run it inside the spreadsheet. If you want to develop inside a separate browser window, i.e. not inside the spreadsheet, you can try opening for example https://localhost:3000/dialog-demo-mui-impl.html. But note the server functions won't work here so you won't see the full app, and it's not really meant to be worked on this way.

**Comment by amadeuscode10** [comment]
Thanks! That worked. I apologize. I seemed to have fundamentally misunderstood the purpose of the localhost and how it worked directly in the add on. This is a great! Thank you for clarification.

**Comment by amadeuscode10** [comment]
Thanks! That worked. I apologize. I seemed to have fundamentally misunderstood the purpose of the localhost and how it worked directly in the add on. This is a great! Thank you for clarification.
