### ISSUE TITLE
Can we migrate to vite?

### ISSUE THREAD

**Issue by KrishnaK-Z** [enuchi/React-Google-Apps-Script#203]
Can we migrate from webpack to vite. In the current setup, whenever there is a state change, the webpack either doesn't reflect the code changes or enters in the infinite loop of build cycle.

**Comment by kapiljhajhria** [comment]
I experience the same issue

**Comment by enuchi** [comment]
Yes, am in the process of updating this project to use `vite`. Will update here once complete.

**Comment by samturner3** [comment]
> Yes, am in the process of updating this project to use `vite`. Will update here once complete.

I checked out your branch `feature/migrate-to-vite` and works for me AFAIK, how close to release it this? I am starting a new project was thinking to wait or use that feature branch as base before I get too far into project in current state on webpack?

**Comment by enuchi** [comment]
I think you can use that branch for your new project. Mostly I need to update the README and some minor configurations, so you should be good to go.
