### ISSUE TITLE
White (blank) sidebar in Chrome when using Station wallet Chrome extension

### ISSUE THREAD

**Issue by adim1973** [enuchi/React-Google-Apps-Script#204]
Hi @enuchi ,

First of all, thank you for this awesome boilerplate, you did a great job!

We have an issue with our add-on, built on top of the boilerplate (I noticed the issue also happens with a fresh clone of the boilerplate and the included sample). The problem is that we are getting a white sidebar after installing the [Chrome Station wallet extension](https://chromewebstore.google.com/detail/station-wallet/aiifbnbfobpmeekipheeijimdpnlpgpp). Once the extension is disabled, the sidebar loads fine.

Any idea why this happens and if something can be done to get the sidebar working?

Thank you for your time,
Adrian

https://github.com/enuchi/React-Google-Apps-Script/assets/5249431/2b95c4f2-b397-4b71-a838-7b7776b41fab

**Comment by enuchi** [comment]
Hi there, not sure I can help you. I'm not familiar with that extension but it could be doing a number of things that block the add-on from loading, such as interfering with loading iframes to loading react in a way that conflicts with this project.

**Comment by adim1973** [comment]
I'm not sure what's happening, the iframe seems to load fine but the content is not rendered.

<img width="953" alt="image" src="https://github.com/enuchi/React-Google-Apps-Script/assets/5249431/d83e68bd-9240-4a7c-9d01-3bdd9bce69a2">

<img width="954" alt="image" src="https://github.com/enuchi/React-Google-Apps-Script/assets/5249431/ff6eed8e-5566-48bb-bf2f-ca660d94c0c7">

**Comment by adim1973** [comment]
Thank you for replying!

1. Other Sheets add-ons with sidebar are working fine with the problematic extension enabled
2. Some html text is displayed correctly

<img width="955" alt="image" src="https://github.com/enuchi/React-Google-Apps-Script/assets/5249431/d7591317-3ff9-4fc6-969e-2298f867823d">

<img width="225" alt="image" src="https://github.com/enuchi/React-Google-Apps-Script/assets/5249431/132e5c73-606d-4c01-8c9a-6e5f3fa408e7">

**Comment by enuchi** [comment]
Hmm maybe you could try not externalizing react and react-dom in production by modifying webpack.config.js.

Find the section below and remove `!isProd &&`? 



   ```
 // don't externalize react during development due to issue with react-refresh
    // https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/334
    if (!isProd && packageName === 'react') {
      return null;
    }
```

**Comment by adim1973** [comment]
Nope, same result.
The problematic extension needs to be installed only, no login/configuration on it.

<img width="728" alt="image" src="https://github.com/enuchi/React-Google-Apps-Script/assets/5249431/a1728124-2a3c-4ded-a6a7-c1270ac3a695">

**Comment by enuchi** [comment]
I'd stick to testing with the provided sidebar app since it is a good minimal example. Looks like your app loads other libraries.

- Try externalizing both react and react-dom:

```js
    if (packageName === 'react' || packageName === 'react-dom') {
      return null;
    }
```

- Can you see if there are any differences in messages/errors printed in the console or requests in network tab with the base sidebar example with problematic add-on turned on vs turned off?

**Comment by adim1973** [comment]
I added the non externalizing react/react-dom code.
![image](https://github.com/enuchi/React-Google-Apps-Script/assets/5249431/2143262e-5c4f-4001-88eb-49dd7cce408e)

But can't see anything obvious difference with the problematic add-on turned on/off.

Elements bad
![image](https://github.com/enuchi/React-Google-Apps-Script/assets/5249431/a2b81bdc-cd45-4c3e-be21-130f5f667b56)

Elements ok
![image](https://github.com/enuchi/React-Google-Apps-Script/assets/5249431/3de8c8de-52e0-4b0e-94cc-8c3d9b2647cc)

Console bad
![image](https://github.com/enuchi/React-Google-Apps-Script/assets/5249431/8e957a08-0ae5-4332-9d84-7baab06f3bda)

Console ok
![image](https://github.com/enuchi/React-Google-Apps-Script/assets/5249431/197071ff-c131-4e21-a79d-86482c681ebf)

Network bad
![image](https://github.com/enuchi/React-Google-Apps-Script/assets/5249431/483c93c9-a744-4d6a-994d-f3e971ba6165)

Network ok
![image](https://github.com/enuchi/React-Google-Apps-Script/assets/5249431/60d472ef-ab56-4152-bf73-485a7e57c8c6)

**Comment by adim1973** [comment]
Downgrading `react/react-dom` to v17.0.2 and adapting `index.tsx` to match react 17 did the trick.
There was probably a conflict with that extension (and possible others).

**Comment by enuchi** [comment]
OK nice. Glad you figured out how to get past it.

**Comment by adim1973** [comment]
Thanks a lot for your help!!!
