### ISSUE TITLE
How to use shadcn/ui

### ISSUE THREAD

**Issue by abidcf** [enuchi/React-Google-Apps-Script#205]
Can anyone help me to configure this project to use shadcn/ui. Any help would be great.
https://ui.shadcn.com/

**Comment by nilooy** [comment]
I will try to write few instructions that i used to set up shadcn/ui

1. Install [Tailwind](https://tailwindcss.com/docs/installation)

```sh
npm install -D tailwindcss
npx tailwindcss init
```

2. Add this line to your `tailwind.config.js` -> content
```
  './src/**/*.{ts,tsx}'
```

3. Init Shadcn

```sh
npx shadcn-ui@latest init
```
> use `./src/client/components` for your component dir and `./src/client/utils` for utils dir when asked by cli

4. create `global.css` file in your `./src/client` dir and add this 

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

5. import this file to your `index.js` of the client folder you want, 
as example, i want to use tailwind into `./src/client/sidebar-about-page`, so for that, i will import the `global.css`
in `./src/client/sidebar-about-page/index.js` like this 
```js
import '../../global.css';
```

6. Now install the components and use following Shadcn's [docs](https://ui.shadcn.com/docs/components/button) 
as example 
```sh
npx shadcn-ui@latest add button

```

Should be good to go!
