### ISSUE TITLE
Issue: app is not loaded when I deploy, but does work with HMR 

### ISSUE THREAD

**Issue by timcastelijn** [enuchi/React-Google-Apps-Script#206]
Hi there,

first of all, your boilerplate project is great, so thanks a lot!

I face an issue though. I am trying to import 'firebase/firestore' in my React Component files. When I include [the import below](https://github.com/timcastelijn/ReactSpreadsheets/blob/2ee968d3317600d8b384bddd396928d1c28bf848/src/client/sidebar-about-page/components/App.jsx#L3), my build gets deployed as expected, but the app doesn't seem to get injected. Also I don't see any debug info.

However, when I serve the app following your [guide for local development](https://github.com/enuchi/React-Google-Apps-Script?tab=readme-ov-file#-local-development-), the app gets injected as expected.

Could you help me pinpoint the issue?

thanks ans best regards,
Tim

I've isolated the issue in my codebase here:
https://github.com/timcastelijn/ReactSpreadsheets/blob/2ee968d3317600d8b384bddd396928d1c28bf848/src/client/sidebar-about-page/components/App.jsx#L3

**Comment by enuchi** [comment]
Can you review #157 and try the changes proposed in #160 ?

There seems to be an issue using firebase and other libraries that use template literals, with Google Apps Script not properly parsing them. Also discussed in #170 .

**Comment by timcastelijn** [comment]
Hi @enuchi ,

Thanks for the quick response. I've tried the changes proposed in #160 and my app now loads as expected after deploying.
