### ISSUE TITLE
Seeing "Running script" with "Cancel" and "Dismiss" instead of "Working" when executing opening the sidebar

### ISSUE THREAD

**Issue by iamsanteri** [enuchi/React-Google-Apps-Script#213]
Thank you for this amazing boilerplate! Since adopting it I'm wondering about one difference to my earlier projects. When I developed and used past editor add-ons, including extensions I downloaded from the marketplace, when opening or working with them I've usually seen "Working" displayed on the bottom of the screen along with spinning arrows which I find intuitive like this:

![working](https://github.com/enuchi/React-Google-Apps-Script/assets/11017096/37b4e17f-1490-4321-a4b8-8985b5199cd2)

However, since I started using this boilerplate project and have been working on my latest add-on I noticed that it shows a bit of a less native output when triggering runs of the script right at the top of the Google Sheet instead, e.g. when opening the about sidebar sample in the project, as follows:

![Screenshot 2024-03-24 at 23 30 14](https://github.com/enuchi/React-Google-Apps-Script/assets/11017096/106a2ebb-1962-4493-993b-9efd812cf0aa)

![Screenshot 2024-03-24 at 23 30 12](https://github.com/enuchi/React-Google-Apps-Script/assets/11017096/9e55271d-be35-4e3c-b2cb-3c702e7e50b5)

![Screenshot 2024-03-24 at 23 31 13](https://github.com/enuchi/React-Google-Apps-Script/assets/11017096/dc0a99dc-ef08-4689-a27a-383e7a84a437)

Is this normal or expected? Is it possible shomehow to adjust this? It really feels like a bummer to me as I can't find any way to get back to my beautiful "Working" spinners from my past add-ons 😄 Indeed, according to some forum posts from across the web these cannot be hidden, but I definitely know that my past add-ons, as well as some of the marketplace ones tend to show "Working" on the bottom instead!

**Comment by enuchi** [comment]
Just tried it out, and once you actually go through the full process of deploying the script as an add-on it will show the "Working" message at the bottom instead of the "Running script" message.

You can try it out by doing a "Test deployment" and trying with an editor add-on.

<img width="255" alt="image" src="https://github.com/enuchi/React-Google-Apps-Script/assets/31550519/b1414b27-a1c2-4431-bfda-e5d4af2a2cac">

**Comment by iamsanteri** [comment]
@enuchi you're doing amazing work with this project and it's just super friendly of you to support people on top of it all. If this is the case and I'll test this out soon, it's just wonderful! This boilerplate is just what I needed and thank you for coming back to me on this one!
