### ISSUE TITLE
ReferenceError: TextEncoder is not defined : how to diagnose a solution

### ISSUE THREAD

**Issue by jmatthewpryor** [enuchi/React-Google-Apps-Script#217]
Hi

I am trying to have server side code that uses [EmailBuilder.js](https://github.com/usewaypoint/email-builder-js) to generate email. I am also using LiquidJS templating to assist in that.

I added those modules to my project, which builds and deploys, but generates this error in onLoad()

`ReferenceError: TextEncoder is not defined     at 911(code:7813:22)     at __webpack_require__(code:9490:45)     at 848(code:9213:47)     at __webpack_require__(code:9490:45)     at 702(code:67:86)     at __webpack_require__(code:9490:45)     at [unknown function](code:9517:20)     at [unknown function](code:9531:7)     at [unknown function](code:9536:3)REFRESH
`
I would appreciate some tips for how to track down the source and resolve the issue

**Comment by enuchi** [comment]
Hmm this looks like a client side library. You can't install packages on the server side of things since it's not running a Node environment (except maybe packages that don't have any dependencies).

**Comment by jmatthewpryor** [comment]
thanks @enuchi - I am pretty much fumbling in the dark here - any further pointers you can give me would be great (or alternative approaches)

**Comment by jmatthewpryor** [comment]
I've worked around it - pushed needed functions to an API
