### ISSUE TITLE
Close dialog in Development Mode using google.script.host.close()

### ISSUE THREAD

**Issue by dhruv9499** [enuchi/React-Google-Apps-Script#225]
Hello Team,

I want to close the dialog programmatically.
`google.script.host.close()` works fine in the production i.e using `yarn run deploy`

but it throws errors in the development mode saying google undefined or not found

**Comment by enuchi** [comment]
See https://github.com/enuchi/React-Google-Apps-Script/issues/104

**Comment by enuchi** [comment]
Now supported in latest version of this project.
