### ISSUE TITLE
[Help needed] - How to use scriptlets?

### ISSUE THREAD

**Issue by mohdabidansari** [enuchi/React-Google-Apps-Script#226]
Tried using scriplets in my frontend code but the transformed code resulted in errors.

**Code**
`
const SHEET_ID = JSON.parse('<?= JSON.stringify(activeSheetId) ?>');
console.log({ SHEET_ID });
`

**Error when running the app**
Uncaught SyntaxError: missing ) after argument list (at userCodeAppPanel:3:6838)

**Comment by enuchi** [comment]
Scriptlets aren't supported here.

**Comment by mohdabidansari** [comment]
So what's the workaround?
Is there any other solution apart from making a request sing serverFunctions when the app loads?

**Comment by enuchi** [comment]
See https://github.com/enuchi/React-Google-Apps-Script/issues/209#issuecomment-1962322152
