### ISSUE TITLE
Debug code

### ISSUE THREAD

**Issue by dboscanv** [enuchi/React-Google-Apps-Script#24]
Hi!
Thanks for this repo, it helps me a lot.

Now I have a issue, I lost the capability in the google apps script editor to debug the functions. For example, `SpreadsheetApp.getActiveSheet()` returns null, but the code works if I call the function from the client side.

How you debug your code in this environment?

**Comment by enuchi** [comment]
What are you trying to do? Run the debugger that comes with the Apps Scripts IDE? Or just track down errors and map them back to your code?

**Comment by enuchi** [comment]
@dboscanv closing but please reopen if you have more questions
