### ISSUE TITLE
Not returning spreadsheet data from the server

### ISSUE THREAD

**Issue by continuata** [enuchi/React-Google-Apps-Script#28]
Urgent ... Please help, trying to set-up a COVID-19 search facility for a charity for self-employed people.

I want to get all the data from a spreadsheet, I've added a handler in `sheet-editor.js` 

```
  const getSheetContentsHandler = () => {
    console.log('getSheetContents', getSheetContents);
    getSheetContents()
      .then(data => {
        console.log('got data', data);
        setData(data);
      })
      .catch(alert);
  };
```
which calls a method in `sheets-utilities.js`

```
const getSheetContents = () =>
  SpreadsheetApp.openById('my-spreadsheet-id')
    .getActiveSheet()
    .getDataRange()
    .getValues();
```

The utility function works fine and I can use `Logger.log` to see it returns the correct spreadsheet data.
But the promise response in my handler function triggers with `data = null` 
I'm not quite sure what's going on under the hood here.
The response from `.getValues()` in the utility seems to be synchronous, so I don't understand why the promise would be resolving to `null`

(the `getSheetsData()` method works fine and returns the names of the sheets in the spreadsheet and I can add sheets too)

**Comment by continuata** [comment]
So after much trial and error, it seems that the `getSheetContents` function although it logs out the data correctly, somehow doesn't evaluate the data when returning from the method.
To make it work, I had to map through the rows and cells of the data.
So this method works:

```
const getSheetContents = () => {
  const data = getActiveDocument()
    .getActiveSheet()
    .getDataRange()
    .getValues();
  return (data || []).map(row => row.map(cell => `${cell}`));
};
```
Seems odd to have to do this. Have I missed something here?

**Comment by enuchi** [comment]
It is strange but I know that there are restrictions on the types allowed in a server response. Does it work if you stringify `data` before returning it?

**Comment by continuata** [comment]
yes doing `JSON.parse(JSON.stringify(data))` does the trick.
Strange one ... I'll close this, seeing as it's nothing to do with your library.

Excellent job BTW:
I've used it to build a free tool for Remote musicians who are out of work with COVID-19
A Google Form inputting to a Google Sheet, and then a React app as a search page on the spreadsheet.
This is an excellent approach ... I'd usually use Google Firebase or AWS, but being able to make forms and sheets so quickly makes this a great option for simple webapps.

**Comment by enuchi** [comment]
Great, glad it's fixed. That is weird. Anyway, adding this link to the scripts docs that talks about allowed types, in case it helps other people reading this:

https://developers.google.com/apps-script/guides/html/reference/run#parameters

**Comment by enuchi** [comment]
And happy to hear this is helpful to you and others right now!
