### ISSUE TITLE
Error in published addon

### ISSUE THREAD

**Issue by lukas1994** [enuchi/React-Google-Apps-Script#29]
Everything works fine in dev but after publishing my [addon](https://gsuite.google.com/marketplace/app/causal/383280853562) I'm getting this error: `We're sorry, a server error occurred while reading from storage. Error code PERMISSION_DENIED.`

I was able to eventually fix this buy moving some of the functions from the generated code to the top of the file. I put these three functions at the top:
```
function onOpen() {
  SpreadsheetApp.getUi().createAddonMenu().addItem("Launch", "openSidebar").addToUi();
}
function onInstall(e) {
  onOpen(e);
}
function openSidebar() {
  var html = HtmlService.createHtmlOutputFromFile("main").setTitle("Causal");
            SpreadsheetApp.getUi().showSidebar(html);
}
```
and removed them from the `global.*`.

Any idea why this is happening? I'd prefer to fix this properly instead of manually rewriting the generated code.

**Comment by enuchi** [comment]
Not sure if you've seen this thread: https://issuetracker.google.com/issues/150247026

Are you logged in to multiple google accounts when you're seeing this issue in your addon?

**Comment by lukas1994** [comment]
yeah I've seen this thread 
now I'm even getting the error after doing the modification described in my initial post
using an incognito tab with only one logged in account also doesn't fix it :/

**Comment by enuchi** [comment]
How about in firefox?

**Comment by lukas1994** [comment]
this is really weird, I just added a console.log statement to the top of the file and now it works
is it usually that buggy or is there something weird going on with my setup?

**Comment by lukas1994** [comment]
one issue could also be that it takes a while to deploy the app, so that I'm seeing old versions

**Comment by lukas1994** [comment]
looks like the issue is actually just moving the functions to the top of the file
is there a way to make webpack do that automatically?

**Comment by enuchi** [comment]
Hmm. Are you running the new chrome v8 runtime or not?

Webpack is already exposing those functions, using [gas-webpack-plugin](  https://github.com/fossamagna/gas-webpack-plugin). That plugin brings any functions attached to `global.*` to the global scope, by first declaring them as functions at the top of the script and then defining the function body below. See line 1 in the [included example app](https://github.com/enuchi/React-Google-Apps-Script/blob/f898046c0664463dc9676f67c7ca82466d4b2439/dist/code.js#L1). If it only works when you define the full `onOpen` function at the top then maybe there are other permissions errors that are throwing in the bundled webpack script. I'm not sure.

Are you running the new chrome v8 runtime? There might be some discrepancies between the new v8 runtime and functions in the global scope but I haven't encountered these.

And does the app work for you if you run the demo app?

**Comment by lukas1994** [comment]
looked like it was a clasp issue,
just created this: https://github.com/google/clasp/issues/761
for now, the work-around is to create the version in the UI

**Comment by lukas1994** [comment]
BTW I'm using v8 if that helps.

**Comment by leopragiclevero** [comment]
@lukas1994 

Help me: https://github.com/google/clasp/issues/761#issuecomment-717770888
