### ISSUE TITLE
problem with fuctions in code.js build(npm run deploy or build)

### ISSUE THREAD

**Issue by marloncepeda** [enuchi/React-Google-Apps-Script#30]
hello I have this problem when I generate the files to create npm run deploy, please help me :( 

`function onOpen() {
}
function openDialog() {
}`

function not have data :( with build

**Comment by enuchi** [comment]
webpack generates the bundles as empty code, but defines them below in the text. Your bundle should look like this:

https://github.com/enuchi/React-Google-Apps-Script/blob/f898046c0664463dc9676f67c7ca82466d4b2439/dist/code.js#L1

Compare with code below in that file:
https://github.com/enuchi/React-Google-Apps-Script/blob/f898046c0664463dc9676f67c7ca82466d4b2439/dist/code.js#L78
