### ISSUE TITLE
Building doesn't use CDN 

### ISSUE THREAD

**Issue by kickbox** [enuchi/React-Google-Apps-Script#31]
Building doesn't seem to source available packages via cdn. 

Eg. I ran the boilerplte with no modifications. Here is the transpiled main.html - https://pastebin.com/u5N8kmWE.

- It has a lot of inlined js 

- Build inlines "react-addons-css-transition-group" js rather than calling via cdn 

Am I missing something here? Please clarify

**Comment by enuchi** [comment]
If you look at the bundled code it is still using the cdn (unpkg.com) to pull in `react`, `react-dom` and `prop-types`, and any other libraries it identifies, which greatly reduces the bundle size. But you're right, it inlines `react-addons-css-transition-group` for some reason. I'll look into why it's doing that. 

You are always going to get some inlined js, which is from the actual code you're writing, such as your components. The reason for inlining is because google apps scripts doesn't allow you to load scripts from external files. The reason for using a cdn is so you don't have to inline libraries like react, and to take advantage of browser caching.

For production builds the js is minified, so it shouldn't be too big, but this will depend on how big your app is.

**Comment by gox-ai** [comment]
Hi enuchi, thanks for getting back. There is `react-addons-css-transition-group` also I tried importing `ant-design` which was also inlined. This makes the app size really big... I am just learning webpack, your setup is really good build using react. Thank you for the good work.

**Comment by enuchi** [comment]
Hi @kickbox @gox-ai, thanks for pointing out the problem with the build. I've made some changes to the repo and the transition group package should be inlined now.

The webpack plugin I've been using, https://github.com/mastilver/dynamic-cdn-webpack-plugin, does not automatically add CDN urls for all packages, only the most popular ones. I've added the ability to add your own in the webpack file, [here](https://github.com/enuchi/React-Google-Apps-Script/blob/be35cda5a3a391629a39dc8cd204ecf5fcb8927b/webpack.config.js#L128-L135).

Do you mind trying it with `ant-design` and letting me know if it works?

Also see the updated explanation in the readme:
https://github.com/enuchi/React-Google-Apps-Script#adding-new-libraries-and-packages

**Comment by enuchi** [comment]
ref #33

**Comment by gox-ai** [comment]
Thank you so much enuchi. Appreciate it. I suddenly have to go bug fixing my other app. I will post the feedback within this week.

**Comment by kickbox** [comment]
Thank you so much enuchi. Appreciate it. I suddenly have to go bug fixing my other app. I will post the feedback within this week.

**Comment by berniegreen** [comment]
I'm having a hard time building after adding the CDNs also. Here is what I added into the webpack.config.js file below the react-transition-group:

`case '@material-ui/core':
              return {
                name: packageName,
                var: 'MaterialCore',
                version: packageVersion,
                url: `https://unpkg.com/@material-ui/core@latest/umd/material-ui.development.js`,
              };
            case '@material-ui/pickers':
              return {
                name: packageName,
                var: 'MaterialPickers',
                version: packageVersion,
                url: `https://unpkg.com/@material-ui/pickers@3.2.8/dist/material-ui-pickers.js`,
              };
            case '@date-io/date-fns':
              return {
                name: packageName,
                var: 'DateFns',
                version: packageVersion,
                url: `https://unpkg.com/@date-io/date-fns@2.6.1/build/index.js`,
              };`

I've never done anything with webpack. Did I do something wrong?

**Comment by enuchi** [comment]
what's the error you're getting when you try to build?

**Comment by enuchi** [comment]
@berniegreen try using `MaterialUI` for the `"var"` value for `@material-ui/core` case?

**Comment by enuchi** [comment]
Hi @berniegreen,

Can you confirm if your code is working? Your bundles are all small so it's hard to tell if you're getting a successful build. Can you open the project successfully in a dialog/sidebar?

Which way are you importing:
```
import CircularProgress from @material-ui/core/CircularProgress
```
or
```
import { CircularProgress } from '@material-ui/core'
```
?

**Comment by berniegreen** [comment]
Hi @enuchi sorry for the delayed response. I scrapped Material UI and decided to go with Semantic UI. I got that working along with some other libraries like GSAP. I wondering though how I use packages that don't have just one file for the CDN. Like react-toastify for example https://www.jsdelivr.com/package/npm/react-toastify Is this possible or only if I include each individual file in the HTML file after building is done?

**Comment by enuchi** [comment]
Hi @berniegreen, sorry for the delayed response. Looks like you should be able to just include the one javascript file that's the entrypoint. Believe it's this one: https://cdn.jsdelivr.net/npm/react-toastify@6.0.6/dist/index.min.js

Note that like a lot of component libraries you'll need to import the css file. Easiest way is to add it to the head tag in the provided html template.

**Comment by enuchi** [comment]
Added some more documentation on how to use the cdn webpack plugin. Feel free to reopen this issue if you still need help.
