### ISSUE TITLE
Test client in local

### ISSUE THREAD

**Issue by kickbox** [enuchi/React-Google-Apps-Script#32]
Is there a way to test the client in local? 

I would like to design the UI, modify css locally to save time. This would save a lot of turn around time.

**Comment by enuchi** [comment]
Yup, there is, it just requires a lot of changes. I haven't had a chance to update the repo, but will do so as soon as I can.

**Comment by gox-ai** [comment]
Hi enuchi, thats great news. Could you give some pointers as to how to do this?

**Comment by enuchi** [comment]
Hi @gox-ai @kickbox 

See my comments on #37 
> Yes. Others are asking (#32) and I'm working on a fully functioning version to include with this repo.
> 
> For now if you want the quick version so you can work locally, you need to install webpack-dev-server, which is what Create React App uses. Just run these commands:
> 
> 1. Install webpack dev server: `npm i -D webpack-dev-server`
> 2. Run webpack dev server: `npx webpack-dev-server --mode development --port 8080`
> 3. Open the page you're working on in the browser: http://localhost:8080/about.html
> 
> Couple of notes:
> 
> * Hot reloading should work. Just save your code changes and the page will reload.
> * As you said, you'll need to mock any server responses. If you actually try to call the server you'll get a `google is not defined` error in the browser. http://localhost:8080/main.html in my example app won't load since it calls the server, but `about.html`.
> * Your page will take up the full screen, so you may want to wrap it in a container that's the size of your dialog/sidebar to see what it will actually look like.
> 
> I have a solution on how to run your local code inside an actual google dialog/sidebar, and call the actual server functions. It works really well, it's just pretty complicated and needs cleaning up. Will post here when I have a version you can try out.

**Comment by kickbox** [comment]
Okay @enuchi your comments seems very interesting. It looks almost impossible to do that. Looking forward to your solution. 

We ca track using the other issue. Closing this.
