### ISSUE TITLE
react-router BrowserHistory and HashHistory support

### ISSUE THREAD

**Issue by amarjayr** [enuchi/React-Google-Apps-Script#34]
Currently if a user wants to use routers for a GAS web app, these is  only support for `MemoryRouter`. This is because GAS' web app sandboxed environment restricts access to APIs `BrowserHistory` and `HashHistory` depend on (ex. `window.history`). 

 I would like to write a Google Apps Script-specific implementations of `BrowserHistory` and `HashHistory` for web app projects by taking advantage of the  following APIs: [google.script.history](https://developers.google.com/apps-script/guides/html/reference/history#eventObject) and [google.script.url](https://developers.google.com/apps-script/guides/html/reference/url). 

@enuchi if I did this would you merge those implementations into this project so they are accessible to those interested in using routers in GAS web apps?

**Comment by enuchi** [comment]
Interesting idea, though not sure how much interest there is in creating webapps with this repo. There was I think one person who asked about that (#15) at some point. The demo project right now doesn't doesn't include a webapp example and in general is more geared towards using dialog windows and/or building add-ons with React. 

Anyway, at the very least if you fork this and add a working example using your custom router I can definitely add a link in the readme to your repo.

**Comment by cobryuk** [comment]
@enuchi So can **react-router-dom** with the webapp not be used at all to simulate multi-page app?

**Comment by connermurphy** [comment]
@enuchi So can we not use react-router-dom at all with webapps? Tried using it but my webapp just loads a blank page.
![Screenshot_2](https://user-images.githubusercontent.com/11260194/95604513-9bf2b200-0a4f-11eb-9933-4d9d35731e89.png)
