### ISSUE TITLE
using development mode in apps scripts?

### ISSUE THREAD

**Issue by mx2323** [enuchi/React-Google-Apps-Script#35]
hi - everything is working pretty well - great project! 

when i push things using 'npm run deploy' (which uses production mode) - everything appears to work fine - although it's difficult to debug because the error messages are quite cryptic in production mode. 

so, i've been trying to use the development mode... but when i try to push the development build using ```
npx webpack --mode development && npx clasp push```

nothing appears to show up in my google sheet. 

anyone know how to push the development version using clasp? this would be really helpful in debugging.

**Comment by enuchi** [comment]
@mx2323 I assume you're trying to debug the server code, right?

You're right, `webpack --mode development` doesn't work. Thanks for pointing this out . I just updated the repo to remove this from the package start script. Try using production mode to build again (`npm run build`) but first adding or changing `minimize: true` to  `minimize: false` [on this line](https://github.com/enuchi/React-Google-Apps-Script/blob/c3802d3afd190e6ba2feff8bc8bcde842dd789d4/webpack.config.js#L168) in the webpack config.

PR:
https://github.com/enuchi/React-Google-Apps-Script/pull/36/files
See comment: https://github.com/enuchi/React-Google-Apps-Script/pull/36#issue-413867765

Reason development mode doesn't work in `gas-webpack-plugin`:
https://github.com/fossamagna/gas-webpack-plugin/issues/135

It's still recommended you use `minify: true` in actual production to reduce bundle size but agree it is difficult to debug. Would like to at some point to add a convenient way to get sourcemaps in this repo but that is a bigger project.

**Comment by mx2323** [comment]
@enuchi I’m trying to debug the client side code ( the react code that is running in the sidebar )

Will try that solution tomorrow and update this case. Thanks!

**Comment by enuchi** [comment]
Ah, got it. So for now, keep it in production mode and add this to the client config:
```
optimization: {
    minimize: false,
},
```
Here:
https://github.com/enuchi/React-Google-Apps-Script/blob/c3802d3afd190e6ba2feff8bc8bcde842dd789d4/webpack.config.js#L76-L101

**Comment by enuchi** [comment]
@mx2323 Updated the config so that development mode doesn't minify. There are new docs in the README that explain how to set up a development environment.

**Comment by enuchi** [comment]
Feel free to reopen this if you still have issues.
