### ISSUE TITLE
error when using images in the project

### ISSUE THREAD

**Issue by ehduardu** [enuchi/React-Google-Apps-Script#40]
I'm using an <img> tag using an image I put inside the project and import into my file, when running "npm run build" I got an error.

![logo_issue](https://user-images.githubusercontent.com/32852890/81813810-4fd22e80-94fe-11ea-9370-b5ec545ece83.png)
![erro_2](https://user-images.githubusercontent.com/32852890/81813827-5496e280-94fe-11ea-976c-991c31b65bdc.png)

**Comment by enuchi** [comment]
The Google Apps Script environment doesn't let you store an image or load it from a relative file path.

You should store your images on a CDN or publicly accessible site somewhere. For a quick, free example, use imgur.

Then use:
```
<img src="https://whereveryoustoredit.com/yourlogopath.png" />
```

Let me know if that works for you. (I'm sorry I haven't documented this anywhere yet.)

**Comment by ehduardu** [comment]
Hi,

Yes, I ended up using a public link and it works well.

Too bad it doesn't work with an image in the project.

Thank you

**Comment by ehduardu** [comment]
Hello,

Yes, I ended up using a public link and it works well.

Too bad it doesn't work with an image in the project.

Thank you
