### ISSUE TITLE
Doesn't transpile server code correctly

### ISSUE THREAD

**Issue by kickbox** [enuchi/React-Google-Apps-Script#42]
I think there some incompatibility rising from ES 6/7 code in the /Server/*.js scripts. 

I found problems when doing these

**1. Using [Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object).X methods**
```
const testData = {
    11: {
      data: 'item',
      dataType: 'cat1',
    },

    12: {
      data: 'item2',
      dataSourceType: 'cat1',
    }
  };

 const result = Object.values(testData); // ERROR HERE
```
Error Message

- GAS Rhino runtime: `Cannot find function values in object function Object() { [native code for Object.Object, arity=1] }`

- GAS V8 runtime: No Error

**2. Using Classes**

```
// Create Customer class as follows:
export default class Customer {}

// Import the class 
import Customer from './path/to/Customer'; 

// Use the class
var customer = new Customer();
var name = customer.getName();  // ERROR HERE
```
Error Message

- GAS Rhino runtime: `TypeError: Cannot find function getName in object [object Object].`
- GAS V8 runtime: `ScriptError: TypeError: this.getName is not a function`

**Comment by enuchi** [comment]
Can you confirm your project is being built and deployed properly with the server code? I'm not able to reproduce your error, and that code works fine for me in Rhino runtime.

Those are the errors you get in the Rhino runtime because `class` and `const` are not available, but the server code gets transpiled into `var` and function-based classes. Please share more about your file structure and what gets generated in your `dist` folder when you run build.

**Comment by gox-ai** [comment]
You are right. I had gobbled up somethings in webpack and babel configurations for the serve code. I recreated the original and things work fine now. A side question, now the App script supports V8 code, is there a way to  transpile to V8 compatible server code?

**Comment by kickbox** [comment]
You are right. I had gobbled up somethings in webpack and babel configurations for the serve code. I recreated the original and things work fine now. A side question, now the App script supports V8 runtime, is there a way to transpile to V8 compatible server code? Would there be performance improvements in doing so?

**Comment by kickbox** [comment]
Am closing this as, it's not an issue with this repository.
