### ISSUE TITLE
"npx clasp push" doesn't execute correctly

### ISSUE THREAD

**Issue by TasseDeCafe** [enuchi/React-Google-Apps-Script#43]
Hi!

I've run all the commands from the readme, and everything worked properly except for the last step: "npm run deploy". The error has to do with clasp, but I don't understand how to fix it. Here's the error when it runs "npx clasp push":

```
  code: 400,
  errors: [
    {
      message: "Syntax error: SyntaxError: Unexpected token 'export' line: 32 file: src/client/server.gs",
      domain: 'global',
      reason: 'badRequest'
    }
  ]
}
```

Thank you for your help!

**Comment by enuchi** [comment]
Looks like clasp is trying to push files in your `src` folder for some reason. Make sure the `.clasp.json` file lists `"rootDir":"dist"` and that your `dist` folder has the proper built files in them  (should be e.g. `code.js`, `main.html`, etc.).

`npm run deploy` first runs `npm run build` then `npm run push`. The first step looks at `src` and builds the proper client and server bundles using your `src`, adding them to the `dist` folder. Then the push step uses clasp to push those files to the google apps script servers.

**Comment by TasseDeCafe** [comment]
Thank you so much, that worked! I probably deleted the original .clasp.json file by mistake during the install since mine only contained the sheet id.
