### ISSUE TITLE
Keep getting "Exception: You do not have permission to call UrlFetchApp.fetch" issue when testing the app

### ISSUE THREAD

**Issue by nathgilson** [enuchi/React-Google-Apps-Script#44]
This error seems to appear randomly. I enabled everything with the auth scopes and the authMode, but it doesn't seem to be related. Any help?

**Comment by enuchi** [comment]
Did you add UrlFetchApp yourself? It is not in the provided sample app.

Normally I've seen this error when 1. I'm logged into multiple accounts -- can you confirm you're only logged into one account? 2. I haven't authorized the app. Sometimes you need to trigger the authorization popup again.

**Comment by nathgilson** [comment]
it works. thank you!

**Comment by enuchi** [comment]
k cool, closing this
