### ISSUE TITLE
error in ./src/server/index.js

### ISSUE THREAD

**Issue by stephenprosso** [enuchi/React-Google-Apps-Script#45]
I have followed the steps to deploy the project and on the last step i run npm run deploy. I have tried several times and I end up with an Error. Module build failed (from ./node_modules/babel-loader/lib/index.js)
Error: cannot find module '@babel/compact-data/corejs3-shipped-proposals'

I cannot seem to get passed this. DO i need to manually configure the dependencies?

**Comment by stephenprosso** [comment]
1. I deleted the package-lock.json file and deleted the node_modules folder. (via file explorer)
2. in package.json file updated devDependencies babel/core and babel/preset-env" to 7.9.0
3. ran npm install 
4. ran npm fund (to fund a few depenencies
5. ran npm run deploy
6.  Manifest file has been updated. Do you want to push and overwrite? **Yes**

Now the dropdown is available in my googlesheet. Thansk!

**Comment by enuchi** [comment]
Hi @stephenprosso, glad you got this working, and thanks for sharing the solution. Will see if I have the same issue on my machine and update the dependencies if necessary.
