### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by kickbox** [enuchi/React-Google-Apps-Script#46]
I can only run my app in incognito mode, where only one user is logged in. If there are more than one gmail session, then I get the following error. 

`ScriptError: We're sorry, a server error occurred while reading from storage. Error code PERMISSION_DENIED.`

I know this is a common issue, but I dont see this error messages with few Add Ons that I install from the store. Any idea on how to handle they are handling the multi session problem?

**Comment by enuchi** [comment]
This is a known error. You can follow this LONG thread here for ideas: https://issuetracker.google.com/issues/69270374

It seems like it's possible that V8 and Rhino versions behave differently, which is one reason this app still tries to be somewhat compatible with both (or would if some of the old babel rules are added).

I don't have an answer for you since my own add-ons now have issues that I thought were solved, but that thread is one place to watch in case the google team provides an update.

**Comment by gox-ai** [comment]
Hi @enuch as described in the forum I contacted gSuite support and got these responses. So, I think opening a support ticket helps in putting pressure on Google to fix the issue. 

> **1**
> Thank you for your patience as we have been investigating this issue. I would like to assure you today that our team continues to actively investigate this issue, and as soon as I receive an update I will contact you immediately.
> 
> I would also like to let you know that you may update this case at any time if you have further questions about this issue, and/or if you find any additional information that you believe would benefit the investigation of this matter.
> 
> 
> **2.**
> I appreciate your time in reaching us regarding this case. Before we proceed, I'd like to set the right expectations with you. Google Apps Script is not part of the G Suite core services defined in the terms of service agreement here [1]. Nevertheless, we will do out best to assist you with this issue.
> 
> After researching, it seems there are others affected by the same behavior when having multiple sign in's on the same browser session. The solution was to disable the V8 engine, [2]. Kindly advise if this fixed the issue? You can find the Stackoverflow discussion here [3].
> 
> The case will remain open while I wait for your response. If you’d like to speak over the phone, let me know by replying to this email with the best contact number and time to call within your timezone. Also if you have any other questions or additional comments, don’t hesitate to reply and I'll be happy to continue helping you.
> 
> [1] https://gsuite.google.com/terms/user_features.html
> [2] https://developers.google.com/apps-script/guides/v8-runtime#enabling_the_rhino_runtime
> [3] https://stackoverflow.com/questions/60442915/container-bound-script-getting-permission-errors-trying-to-run-functions-with-go

**Comment by kickbox** [comment]
Hi @enuch as described in the forum I contacted gSuite support and got these responses. So, I think opening a support ticket helps in putting pressure on Google to fix the issue. 

> **1**
> Thank you for your patience as we have been investigating this issue. I would like to assure you today that our team continues to actively investigate this issue, and as soon as I receive an update I will contact you immediately.
> 
> I would also like to let you know that you may update this case at any time if you have further questions about this issue, and/or if you find any additional information that you believe would benefit the investigation of this matter.
> 
> 
> **2.**
> I appreciate your time in reaching us regarding this case. Before we proceed, I'd like to set the right expectations with you. Google Apps Script is not part of the G Suite core services defined in the terms of service agreement here [1]. Nevertheless, we will do out best to assist you with this issue.
> 
> After researching, it seems there are others affected by the same behavior when having multiple sign in's on the same browser session. The solution was to disable the V8 engine, [2]. Kindly advise if this fixed the issue? You can find the Stackoverflow discussion here [3].
> 
> The case will remain open while I wait for your response. If you’d like to speak over the phone, let me know by replying to this email with the best contact number and time to call within your timezone. Also if you have any other questions or additional comments, don’t hesitate to reply and I'll be happy to continue helping you.
> 
> [1] https://gsuite.google.com/terms/user_features.html
> [2] https://developers.google.com/apps-script/guides/v8-runtime#enabling_the_rhino_runtime
> [3] https://stackoverflow.com/questions/60442915/container-bound-script-getting-permission-errors-trying-to-run-functions-with-go

**Comment by enuchi** [comment]
Thanks @kickbox. It looks like the error still exists but appreciate you opening the ticket with the google team. Hopefully they fix this bug soon.

**Comment by kickbox** [comment]
Yes, they gave an ETA of September - Hopeful:+1: . I have been able to reproduce the issue consistently. The issue happens when accessing `properties service` when multiple google sessions exist in browser.

**Comment by abhinav-adtechs** [comment]
I was able to reproduce this issue with this scenario – If you have multiple google accounts logged in and the account you are installing in is not the primary account you will face this PERMISSION_DENIED issue. I was able to fix this error by making the account as the only account in the google space
![Screenshot 2023-05-10 at 10 07 58 PM](https://github.com/enuchi/React-Google-Apps-Script/assets/13555405/8d2bc06e-4cb5-442e-8b4d-80ef8644f1d6)

**Comment by subwizzll** [comment]
> I was able to reproduce this issue with this scenario – If you have multiple google accounts logged in and the account you are installing in is not the primary account you will face this PERMISSION_DENIED issue. I was able to fix this error by making the account as the only account in the google space ![Screenshot 2023-05-10 at 10 07 58 PM](https://private-user-images.githubusercontent.com/13555405/237458565-8d2bc06e-4cb5-442e-8b4d-80ef8644f1d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NzQ5MzYsIm5iZiI6MTcyODg3NDYzNiwicGF0aCI6Ii8xMzU1NTQwNS8yMzc0NTg1NjUtOGQyYmMwNmUtNGNiNS00NDJlLThiNGQtODBlZjg2NDRmMWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDAyNTcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MGZjMjM0NTZiMDI0ZjFkYmRhMjU1YTk5NDg1ZWZhZTIwYzc3MzU3MzdkZTVlNDFlNjhjMzAzMWUzYzc1M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.udahAEYHh2wekL98ED8gk1FGDO9orLugNI_4mKAU2tQ)

this solved the issue for me.
