### ISSUE TITLE
Do you intend to add Web app functionality too via app script in this project? Thanks for this great project!

### ISSUE THREAD

**Issue by kk-ssc** [enuchi/React-Google-Apps-Script#55]

**Comment by kk-ssc** [comment]
That helped. Thank you, I am planning on creating a personal to do list project :)

**Comment by kk-ssc** [comment]
> apps

That helped. Thank you.. I am planning on creating a personal to do list project :)

**Comment by soql101** [comment]
@enuchi  Hi , I followed step as above but I am getting error 'ScriptError: Exception: Please select an active sheet first.' i am not able to set activate sheet for web app till now I come up with `SpreadsheetApp.openById('1mDmI_iPp0RYXG5Os7F.......').setActiveSheet('Sheet1');`
also wondering in which function I need to add this . Your help really appreciated

**Comment by enuchi** [comment]
Hi @soql101 , have you tried updating here? Although not sure why you would need this.

https://github.com/enuchi/React-Google-Apps-Script/blob/e73e51e56e99903885ef8dd5525986f99038d8bf/src/server/sheets.js#L29

**Comment by soql101** [comment]
@enuchi  thanks for your input.

If someone land on same question while working with Web App, here is fix

In sheets.js 
**Replace all**  `SpreadsheetApp.getActive()` with `SpreadsheetApp.openById('<sheetId>')`

Example 
`const getSheets = () => SpreadsheetApp.getActive().getSheets();
`
replace with 

`const getSheets = () =>SpreadsheetApp.openById('<sheetId>').getSheets();
`

**Heads up** : setActiveSheet arrow function will not work in web app
why ?

In order for something to be active, it must be open in the browser.
The code:
SpreadsheetApp.getActive().
Gets a Google Sheet that is already open in the browser.
But
SpreadsheetApp.openById(SHEET_ID) 
Doesn't open up a Sheet in the browser.
You can't activate something that isn't open in the browser.
The activate() method will never work with SpreadsheetApp.openById(SHEET_ID)

https://github.com/enuchi/React-Google-Apps-Script/blob/e73e51e56e99903885ef8dd5525986f99038d8bf/src/server/sheets.js#L28
