### ISSUE TITLE
Not able to use react-router package

### ISSUE THREAD

**Issue by kk-ssc** [enuchi/React-Google-Apps-Script#56]
I tried to install "react-router" package

And then proceeded with navigation using this package. But that does not work.
 
For an instance: script_url/home where home is my parameter does not load the component

**Comment by enuchi** [comment]
Are you trying to use it with a web app? You would need to figure out how to use with google.script.history.

See https://developers.google.com/apps-script/guides/web#web_apps_and_browser_history

Also see https://github.com/enuchi/React-Google-Apps-Script/issues/34.

**Comment by connermurphy** [comment]
@enuchi So can we not use react-router-dom at all with webapps? Tried using it but my webapp just loads a blank page.
![Screenshot_2](https://user-images.githubusercontent.com/11260194/95604602-b62c9000-0a4f-11eb-80a6-f39e6503730a.png)

**Comment by enuchi** [comment]
Nope, doesn't appear so. Did you check out the link to the google documentation? https://developers.google.com/apps-script/guides/web#web_apps_and_browser_history

Web apps use their own API, `google.script.history`, to support navigation, whereas react-router uses the native browser API, so they wouldn't be compatible. To navigate to different pages you'll have to write your own "router". See this page for examples on how to navigate to new pages: https://developers.google.com/apps-script/guides/html/reference/history

I should note `google.script.history` wouldn't work in local development.

**Comment by enuchi** [comment]
Going to close this but reopen if you have more questions.
