### ISSUE TITLE
Multiple html templates

### ISSUE THREAD

**Issue by ralphilius** [enuchi/React-Google-Apps-Script#6]
Hello,

As configured in webpack.config, this setup will only have dialog. What if I want to have sidebar? I can copy tasks, but for more files, it would be difficult and not productive.

**Comment by ralphilius** [comment]
Okay. I've copied and made another webpack config for sidebar and dialog.

**Comment by enuchi** [comment]
Closing but can reopen if more demand for this.

**Comment by enuchi** [comment]
This now includes support for multiple dialogs/sidebars. See updated readme here:
https://github.com/enuchi/React-Google-Apps-Script#multiple-dialogs
