### ISSUE TITLE
Had an issue setting NODE_ENV on windows - "ENOENT: no such file or directory, open 'dist\appsscript.json'"

### ISSUE THREAD

**Issue by RCRJ** [enuchi/React-Google-Apps-Script#61]
Hey again @enuchi,

I had the opportunity to upgrade my project recently to the newest version you've published. However, even using the starter demo you provided, I was having some issues with the commands:

    "build:dev": "NODE_ENV=development webpack",
    "build": "NODE_ENV=production webpack",

This was likely due to being on Windows, but even so, I had no luck adding "SET " before "NODE_ENV". I ended up finding the below module and was able to fix the issue by following their instructions.

Not sure if you need to update the project, I just wanted this to be here if someone else has the same problem.

**module:** https://www.npmjs.com/package/cross-env
**Original Error Message:** ENOENT: no such file or directory, open 'dist\appsscript.json'
**Likely issue:** Due to being on Windows

**Comment by enuchi** [comment]
Ah hi @RCRJ 

Yes, someone else mentioned the same issue and I never got around to updating. Oops!

Here's the referenced issue: https://github.com/enuchi/React-Google-Apps-Script/issues/57#issuecomment-685139860

Do you want to open a PR with your changes? I don't have Windows so it's hard for me to test.

**Comment by enuchi** [comment]
Fixed by https://github.com/enuchi/React-Google-Apps-Script/pull/63. Thanks @RCRJ for this.
