### ISSUE TITLE
Dist folder not populating

### ISSUE THREAD

**Issue by connermurphy** [enuchi/React-Google-Apps-Script#62]
I've followed the steps exactly, the only change I've made is in package.json is to `SET NODE_ENV` to work on Windows. I run `npm run setup` and then `npm run deploy` and the only thing in my **dist** folder is my **appsscript.json** file. 

![Screenshot_1](https://user-images.githubusercontent.com/11260194/95596347-300b4c00-0a45-11eb-80a1-6e31c2499ca5.png)

**Comment by enuchi** [comment]
See https://github.com/enuchi/React-Google-Apps-Script/issues/61.

Can you try installing `cross-env` and changing the scripts to to `cross-env NODE_ENV=production ...`?

**Comment by connermurphy** [comment]
Yeah, I literally just thought it could potentially be that issue and it was. Thanks for the reply!
