### ISSUE TITLE
Custom functions support (With auto complete)

### ISSUE THREAD

**Issue by leopragiclevero** [enuchi/React-Google-Apps-Script#64]
Google Apps script support custom functions. (https://developers.google.com/apps-script/guides/sheets/functions). I can include the custom function and assign it to the global scope. The problem with that it will not support auto-complete since webpack stripes of the comments. 

Note: Custom functions will appear in this list if their script includes a JsDoc @customfunction tag
Eg: 
```
/**
 * Multiplies the input value by 2.
 *
 * @param {number} input The value to multiply.
 * @return The input multiplied by 2.
 * @customfunction
 */
```

**Comment by enuchi** [comment]
Can you add a description @leopragiclevero ? Not sure what you're referring to.

**Comment by leopragiclevero** [comment]
> Can you add a description @leopragiclevero ? Not sure what you're referring to.

Added! and also found a solution.

**Comment by leopragi** [comment]
You can do it with `CopyWebpackPlugin`. My setup is that I have a `functions` folder on under root where I have multiple JS files. Each JS file can have its own custom function. In Webpack I simply copy the functions/*.js to dist/*.js (converted to GS file on uploading). 

Now this will copy the custom function files without any modification to the google apps script with @customfunction tag. 

NOTE: Since all server-side functions all under global scope you can use any util/common function directly on your custom function code.

**Comment by enuchi** [comment]
Yep, looks like this is almost possible with the current setup, just needs a small change to the webpack server config.

Add `comments: 'function'` to the `terserOptions.output` configuration:
```js
output: {
   beautify: true,
   comments: 'function',
},
```
This is the section here:
https://github.com/enuchi/React-Google-Apps-Script/blob/dc3613395cd2d33ded54c38c1d127d91cbeca31b/webpack.config.js#L290-L312

Then add your jsdoc documentation to the function and assign to the global object, as you were doing:
```js
/**
 * Multiplies the input value by 2.
 *
 * @param {number} input The value to multiply.
 * @return The input multiplied by 2.
 * @customfunction
 */
global.DOUBLE = input => input * 2;
```

After you run `npm run deploy` you should see autocompletion for your custom function.

![custom function](https://user-images.githubusercontent.com/31550519/96670221-d6e8c580-132c-11eb-98bb-a90a7adcec63.gif)

**Comment by enuchi** [comment]
Actually, even better:
```js
output: {
   comments: /@customfunction/,
},
```

**Comment by leopragi** [comment]
> Actually, even better:
> 
> ```js
> output: {
>    comments: /@customfunction/,
> },
> ```

Did you check this by pushing the codes to GAS? Yesterday I did try this but didn't work for me.

**Comment by enuchi** [comment]
Yes, the image I shared was from after I pushed the changes. I'll update the repo with these changes soon.

**Comment by leopragi** [comment]
Cool @enuchi, I ll close the issue once i try the `comments: /@customfunction/`
