### ISSUE TITLE
Support ES2020

### ISSUE THREAD

**Issue by kickbox** [enuchi/React-Google-Apps-Script#65]
Hey @enuchi`, when using [ Nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator), the build fails with the following error. Am not sure which webpack config to change in this regard. Could you please guide.

```
Module parse failed: Unexpected token (90:35)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     allowClear: true,
|     treeNodeFilterProp: "searcher"
>   }, (initialValues.metrics.items ?? []).map(group => /*#__PURE__*/React.createElement(TreeSelect.TreeNode, {
|     selectable: false,
|     value: group.group,
```

**Comment by enuchi** [comment]
Looks like you'll need to install the plugin: `npm install --save-dev @babel/plugin-proposal-nullish-coalescing-operator`

Then try adding `"@babel/plugin-proposal-nullish-coalescing-operator"` to the list of plugins in https://github.com/enuchi/React-Google-Apps-Script/blob/master/src/client/.babelrc and/or https://github.com/enuchi/React-Google-Apps-Script/blob/master/src/server/.babelrc

Let me know if it works.

**Comment by kickbox** [comment]
Hi, @enuchi thank you. I added in client as that's where I used the `??` operation. It's working beautifully.
