### ISSUE TITLE
How to run as a Google App Script Library?

### ISSUE THREAD

**Issue by kingarawana** [enuchi/React-Google-Apps-Script#67]
This project seems to work fine when I publish the code to a script attached to a specific Google Sheet, but when I convert it to a Library by following these [docs](https://developers.google.com/apps-script/guides/libraries), basically by creating a version, then in another Google Sheet editing it's script to add the library I just created (also documented in that link).

When I do that and I update the function name argument to include the library id, e.g 'openSidebar' -> 'libraryId.openSidebar`, it opens the sidebar as usual, but when I try to call my 'server' functions, it says `serverFunctions[functionName] is not a function`.

Is this a bug? or is there a configuration I can set to make so that my script is Library compatible?

**Comment by enuchi** [comment]
Not sure I understand what you're trying to achieve @kingarawana . Are you trying to run a library function from the react app?

**Comment by stephensilber** [comment]
I'm running into a similar issue. I've deployed this to my sheet but even the example functions throw the `TypeError: serverFunctions[functionName] is not a function`.

**Comment by brentadamson** [comment]
Not sure if it's the case for you but here's what worked for me:

1. Make sure your function is exported `export const myfunction = () => { return 'blah'; }`
2. Add `global.myfunction = myfunction;` to your server-side code: https://github.com/enuchi/React-Google-Apps-Script/blob/master/src/server/index.js
3. Stop your server with `ctrl+c`, then start it again.
4. Open up your sidebar or modal.

In my case, I had to do all four steps. Steps 1-3 weren't enough.

**Comment by enuchi** [comment]
Please reopen if you have more information on how to reproduce.
