### ISSUE TITLE
Listen for spreadsheet events in ui

### ISSUE THREAD

**Issue by PopeOnARope** [enuchi/React-Google-Apps-Script#68]
Is there a proper way to use `onSelectionChange` or other listeners to update the ui? for example, I want my react app to know when the user selects a new cell, and I want to update my app with the content of that cell.

I am trying to pass my react dispatch method to the `onSelectionChange` in server functions:
```
// react app
import React from 'react';
export const initialState = { currentView: 'chatWindow' };
export const GlobalStore = React.createContext(initialState);
export const useGlobalStore = () => React.useContext(GlobalStore);
```

```
// server/index.js
import { useGlobalStore } from '../client/screen-app/store';
global.onSelectionChange = e => {
  const { dispatch } = useGlobalStore();
  dispatch({ type: 'row', value: someValue });
};
```
Thanks for creating this template, it's been great to work with!

**Comment by enuchi** [comment]
Hey @PopeOnARope , great question. There is probably a workaround, but it would be a very hacky solution.

The way you're trying won't work. You can't share code like that between client and server. They are essentially two different apps that get bundled separately: a client app and a server app. The server (Google Apps Script) code doesn't know anything about react so can't use context.

The only way to communicate between client and server is through the `google.script.run` api, which I've wrapped with a `"gas-client"` package that tries to simplify things and let you easily call server functions. `onSelectionChange` is basically its own, separate, server function that gets called whenever you select something new. I don't know how you could trigger something in the react app that was initiated from the server code.

You could do something like poll the server on an interval or something but can't think of a simple solution off the top of my head.

**Comment by PopeOnARope** [comment]
Thanks so much for the reply! I ended up having my component query the server at an interval, but wasn't sure if there was a built-in way to listen for changes from the ui. This is my first time working with Google Apps Script, so still figuring it out!
