### ISSUE TITLE
Typescript- web api

### ISSUE THREAD

**Issue by ieow** [enuchi/React-Google-Apps-Script#69]
Nice work on typescript. :)

I tried use typescript with web api on client side code, but got complaint of 
Cannot find name 'window'.ts(2304)

I tried set tsconfig below but still the same.
{
  "compilerOptions": {
    "lib": [ "es2015", "es6", "DOM" ],

    "noImplicitAny": true,
    "module": "commonjs",

    "types": ["gas-types-detailed"],
    "jsx": "react",
    "esModuleInterop": true
  },
   
}

Am I missing some configuration ?

**Comment by enuchi** [comment]
did you figure this out @ieow ?

**Comment by ieow** [comment]
Yes.
The config works. 
I just need to restart vscode. Thanks.

Btw, for the gas-client typescript, is the PR going well?
I am using  @romstar/gas-client-typescript for now
