### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by georgewritescode** [enuchi/React-Google-Apps-Script#7]
Hi!
Great project. I noticed in package.json you have the license as MIT, however, there is no license file in the directory. I think this would help clarify the license and it would follow what other projects do.

What do you think? Here is a helpful guide for adding the MIT license file.
https://help.github.com/en/articles/adding-a-license-to-a-repository

Thanks,
George

**Comment by enuchi** [comment]
Done, thanks!
