### ISSUE TITLE
appendRow's input type should be any[] typed in google-apps-script.spreadsheet.d.ts

### ISSUE THREAD

**Issue by ieow** [enuchi/React-Google-Apps-Script#72]
Although in the goolge app script document mention that the input type is object , in typescript string is not cast able to object type.
This is causing the input of appendRow with string type got flagged by typescript

appendRow's input type should be any[] typed in google-apps-script.spreadsheet.d.ts as per @types/google-apps-script

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-apps-script/google-apps-script.spreadsheet.d.ts
line 1814 (spreadsheet) and 1633 (sheet) :
```  appendRow(rowContents: any[]): Sheet; ```

**Comment by ieow** [comment]
same issue for the method getSheetValues. It should be returning any[][] instead of object[][] 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-apps-script/google-apps-script.spreadsheet.d.ts
line 1863  and 1697:
      getSheetValues(startRow: Integer, startColumn: Integer, numRows: Integer, numColumns: Integer): any[][];

**Comment by enuchi** [comment]
Hm thanks for pointing out. I made a fork that has more detailed docs: https://www.npmjs.com/package/gas-types-detailed

But it may have mistakes, as you pointed out. For now you can remove this package and install @types/google-apps-script, and you may be able to get more up-to-date type definitions.

**Comment by ieow** [comment]
I forgot to mention that I was planning to file the issue at github.com/enuchi/gas-types-detailed
but I got 404. So I can only file it here.
Sorry for the lack of info

**Comment by ieow** [comment]
additional finding.

in google-apps-script.base.d.ts  
line 14

interface Blob need to extend BlobSource
```
    interface Blob extends BlobSource {
```

**Comment by enuchi** [comment]
Sorry, I had it as private. I just made it public -- can you add issues and/or feel free to open a PR there:
https://github.com/enuchi/gas-types-detailed

See this thread and fork on how to generate the docs in case that needs to get updated:
https://github.com/PopGoesTheWza/dts-google-apps-script/pull/2
https://github.com/enuchi/dts-google-apps-script/

**Comment by enuchi** [comment]
I created gas-types-detailed to include full descriptions on each class/method from the official Google docs. However it is out of date and probably some of the types are wrong/missing.

DefinitelyTyped's @types/google-apps-script doesn't have descriptions but the types are more likely to be accurate and up to date.

**Comment by jsbrain** [comment]
Yeah I just realized that even though the name suggests it. My bad but thanks for the heads up!

**Comment by enuchi** [comment]
Hi @ieow @jsbrain I updated this package addressing the issues you mentioned and republished as [gas-types-detailed@1.1.0](https://www.npmjs.com/package/gas-types-detailed).

PR with changes here: https://github.com/enuchi/gas-types-detailed/pull/2

Sorry for taking a while on this one. Please reopen if you find other issues with the package.
