### ISSUE TITLE
Server-side functions slugginesh problem

### ISSUE THREAD

**Issue by coccoinomane** [enuchi/React-Google-Apps-Script#73]
First of all, congratulations for this great package: it is really helpful being able to use React on Google Apps Scripts!

I have installed the demo project, but when using the Sheet Editor, it takes a really long time (>5s) to load the sheets list; [here's a screencast of the issue](https://idearia.link/JSZT2I). The same happens with my own scripts.

Is the delay expected?

Thank you,
Guido

**Comment by coccoinomane** [comment]
It seems the issue was related to slowness on Google side, I am closing this issue.

**Comment by enuchi** [comment]
Thanks for the update @coccoinomane. Glad you find this project useful!
