### ISSUE TITLE
React Developer Tools Chrome Extension

### ISSUE THREAD

**Issue by coccoinomane** [enuchi/React-Google-Apps-Script#74]
Hello,
I was wondering it there was a way to use the Rect Dev Tools Chrome extension on dialogs and sidebars created with this project.
When I try to do so, I get the message "This page doesn’t appear to be using React" ([screenshot](https://idearia.link/sJOOuF)).
Thank you,
Guido

**Comment by enuchi** [comment]
Sorry @coccoinomane, I haven't been able to look into this. Did you figure something out?

**Comment by coccoinomane** [comment]
Hi @enuchi ! I did not manage to make it work, but it's no big issue :-)

**Comment by enuchi** [comment]
Hey @coccoinomane  -- actually got this to work anyway! Posting details here in case it's useful for others.

Looks like you need to use the "standalone" version of React Dev Tools when the React App is running in an iframe ([more details here](https://github.com/facebook/react/tree/master/packages/react-devtools#usage-with-react-dom)).

Pretty easy to set up:

1. In your repo install the Dev Tools tool: `npm install -D react-devtools`
2. In a new terminal window run `npx react-devtools` to launch the Dev Tools app.
3. Add `<script src="http://localhost:8097"></script>` to the top of your `<head>` in your react app. For example, I added this line to the [index.html](https://github.com/enuchi/React-Google-Apps-Script/blob/e73e51e56e99903885ef8dd5525986f99038d8bf/src/client/dialog-demo-bootstrap/index.html) file in the sample bootstrap app.
4. Deploy your app and you should see the Dev Tools showing your app.

![Mar-07-2021 23-08-15](https://user-images.githubusercontent.com/31550519/110273600-ee9eae80-7f9a-11eb-9796-31353b47dfa8.gif)

Don't forget to remove the `<script>` tag before deploying to production.

**Comment by coccoinomane** [comment]
Impressive, thank you for the workaround! 
Maybe it's worth including it in the README?

**Comment by RealSlimMahdi** [comment]
Thank you @enuchi for your work, this is a very useful project, I am glad I heard of it in Reddit.

**Comment by enuchi** [comment]
Thank you @RealSlimMahdi!

**Comment by enuchi** [comment]
@coccoinomane I added the notes from above to the README.
