### ISSUE TITLE
Is it possible to pass template variables?

### ISSUE THREAD

**Issue by brentadamson** [enuchi/React-Google-Apps-Script#76]
Is it possible to pass template variables to the client when, say, the sidebar is loaded?
https://stackoverflow.com/a/56641255/522962

If not, I guess the workaround would be to query the server when the sidebar loads?

**Comment by enuchi** [comment]
Hi @brentadamson, it wouldn't work with this build setup, and it isn't actually recommended by Google. While their documentation explains how to use template variables, they also say to ["Load data asynchronously, not in templates"](https://developers.google.com/apps-script/guides/html/best-practices#load_data_asynchronously_not_in_templates).

As you mention, the idea is to call the server when you load the sidebar. You can see how this is done in the examples I include with this repo: 
https://github.com/enuchi/React-Google-Apps-Script/blob/18fb03d42c52294c6f1c399a996800aead503385/src/client/dialog-demo/components/SheetEditor.jsx#L14-L20

**Comment by brentadamson** [comment]
Great work on this! Thanks!
