### ISSUE TITLE
Unsafe attempt to initiate navigation for frame with origin 'https://docs.google.com' from frame with URL 'https://localhost:3000/taxonomytool-impl.html'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

### ISSUE THREAD

**Issue by WillLiuMH** [enuchi/React-Google-Apps-Script#82]
Hi!

I am trying to add a link for users to give feedback on my gsheets web app. However I keep getting the error `Unsafe attempt to initiate navigation for frame with origin 'https://docs.google.com' from frame with URL 'https://localhost:3000/taxonomytool-impl.html'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.` whenever I click on the link. 

I understand I just need to set the 'allow-top-navigation-by-user-activation' sandbox attribute on the iframe, but am struggling how to do so from this library since we never declare the iframe itsself anywhere. When I ctrl+f for iframe, I only see one tag and it looks like its in the dev index.js. 

I suspect I can modify this code in the server `ui.js` file to add the attribute, but looks like I can't call `setAttribute` here. Anyone have any ideas?

```export const openTaxonomy = () => {
  const html = HtmlService.createHtmlOutputFromFile('taxonomytool')
    .setWidth(900)
    .setHeight(900);
  SpreadsheetApp.getUi().showModalDialog(html, 'Taxonomy Builder');
};
```

**Comment by WillLiuMH** [comment]
Hey @enuchi, yeah I'm getting the same issue in both the development and deployed versions. I just need get that attribute set on the iframe somehow and I think it should be good, but just scratching my head at how to do that...

Also just wanted to say thanks for writing this library. It's been kick ass so far!

**Comment by enuchi** [comment]
Glad it's been helpful to you!

If I understand what's happening correctly then you are not going to be able to modify the top level iframe because Google does not expose that capability. I don't believe you're able to navigate to another page within the iframe -- can you take a look here? https://developers.google.com/apps-script/guides/html/restrictions#restrictions_in_iframe_mode

What happens if you add a link with the target="_top" attribute?
```html
<a href="http://google.com" target="_top">Click Me!</a>
```

**Comment by WillLiuMH** [comment]
Hmmm I tried that, no change. Looking at the article you linked, the `_top` attribute is actually supposed to go into the <base> tag in the html sheet, which you already had there. I feel like there's got to be a way!!!

**Comment by enuchi** [comment]
I don't think it's going to work. I'm guessing Google really doesn't want you to navigate to another page within its UI, for security reasons. Your best bet is to launch your page in a new tab with target _blank: `<a href="http://www.yourpage.com" target="_blank">`

**Comment by WillLiuMH** [comment]
Ahhh yeah I think I'm finding that too. Honestly though new tab is not a bad alternative. Thanks for your help here @enuchi and appreciate all the work you've put into this library!
