### ISSUE TITLE
Client JS not getting the sheet from serverFunctions.getActiveSpreadsheet()

### ISSUE THREAD

**Issue by thenrich2009** [enuchi/React-Google-Apps-Script#84]
I added a new function in sheets.js : `export const getActiveSpreadsheet = () =>  SpreadsheetApp.getActiveSpreadsheet();`
Defined it globally in index.js: `global.getActiveSpreadsheet = publicSheetFunctions.getActiveSpreadsheet;`

in my client code I have this:
```
serverFunctions.getActiveSpreadsheet().then(ss => InsertRow(ss))
       .catch(err => console.log(err));

    function InsertRow(ss) {
        var rowLast = ss.getLastRow();
        ss.insertRowAfter(rowLast);
    }
```

However I get an error that getLastRow is not a function. In the debugger, ss seems to be an empty object. Shouldn't it be the active sheet returned from the server getActiveSpreadsheet()?

**Comment by enuchi** [comment]
Hi @thenrich2009 , [getActiveSpreadsheet()](https://developers.google.com/apps-script/reference/spreadsheet/spreadsheet-app#getactivespreadsheet) returns a "Spreadsheet object" which is an internal server-side representation of a spreadsheet. You can only use these types of objects on the server.

To communicate between server and client you can only pass serializable objects back and forth such as string, array, etc. See here for more [info on types](https://developers.google.com/apps-script/guides/html/communication#parameters_and_return_values). To accomplish what you are trying to do, you will probably need to get send the name of the spreadsheet you want to add rows to from the client. See the examples provided.

**Comment by thenrich2009** [comment]
Thanks. I created a bunch of server side functions.
