### ISSUE TITLE
Nested clasp projects are not supported - npm run setup

### ISSUE THREAD

**Issue by ShreyP88** [enuchi/React-Google-Apps-Script#89]
Hi, I've been following the instruction 1:1; however, when I run 'npm run setup,' I get the error as seen in the attachment below.

![nested clasp project](https://user-images.githubusercontent.com/69047353/117701152-e3cbea00-b194-11eb-8374-d11eb8f577f9.png)

I would appreciate some guidance, thanks!

**Comment by enuchi** [comment]
@ShreyP88 I think I've seen this before. You may have put this clasp project inside another one. Can you check the parent directory (and all the parents) and make sure there's no .clasp.json file in any of those directories?

**Comment by ShreyP88** [comment]
Yea, I checked that before but the only clasp file I saw was when I cloned the project, after running npm run setup it's delete and I can't find any other clasp.json.

**Comment by enuchi** [comment]
Did you figure it out @ShreyP88?

**Comment by ShreyP88** [comment]
Yea, sorry about that, I didn't think to check in my user directory. Brushed it off as I didn't believe that it could have possibly been there but it was. Thanks for the help!
