### ISSUE TITLE
Strange issue... ERR_CONNECTION_REFUSED...can't pin down why this issue is happening.

### ISSUE THREAD

**Issue by WillLiuMH** [enuchi/React-Google-Apps-Script#90]
80% of the time, my app works fine. However, sometimes when I need to redeploy or `npm run start` again, something breaks and I receive these errors when opening up the app: 

`GET http://localhost:8097/ net::ERR_CONNECTION_REFUSED`
`react-redux.min.js:9 Uncaught TypeError: Cannot read property 'unstable_batchedUpdates' of undefined
    at react-redux.min.js:9`
`Io {message: "There was an error during the transport or process…this request. Error code = 10, Path = /wardeninit", name: "TransportError", stack: "TransportError: There was an error during the tran…/js/2633236535-warden_bin_i18n_warden.js:195:263)"}`

The function to open the modal runs successfully, but then these errors occur and only a blank modal page is shown. 

The strange thing is that usually some combination of re-deploying, emptying the cache, signing out of my Google account and back in, will fix this issue. However, not all of these work as the solution 100% of the time. It's so weird. Sometimes I try all of them and nothing has worked, but when I try again later it does work. Then the next time I re-deploy the issue comes up again. 

I'm so curious what this issue might be related to. 

I am using redux, and the 2nd error points to an error with redux. However, I think it's more likely that somehow the app is just not loading correctly when I run the deploy script and that is what is causing the redux error. When I look at the code in the script editor, it looks normal. 

I'll also add that this error doesn't happen EVERY time I re-deploy. Sometimes I can go from local development, deploy, and then the error will happen when I `run npm start`. Then sometimes I'm stuck with this error in the deployed version and when I run `npm run start` it will actually fix the issue. It's SO WEIRD. 

Has anyone else encountered anything like this? Not expecting anyone to know the answer but if you have any ideas on anything I should test or investigate please let me know. I don't even know where to start.

**Comment by WillLiuMH** [comment]
So I've determined this is 100% due to redux. I pulled a clean copy of this repo and added redux to it, started getting the error again. The weird thing is the error will still happen only some of the time, without any of the code changing. The only thing that is changing is me `npm run start` and `npm run deploy` over and over again.

**Comment by sjoshuadarth** [comment]
I've been experiencing the same. Sometimes the prod deploy would work by deploying it to a new version from the GAS editor. I'm not able to pinpoint what's wrong with redux because the same app running on a normal react app is running smoothly.

**Comment by enuchi** [comment]
@WillLiuMH or @sjoshuadarth happy to look into this. Can you explain how to reproduce?

**Comment by sjoshuadarth** [comment]
[https://github.com/sjoshuadarth/react-gas-test](Test)

The issue is still present, I created a new clasp version for this. Deployed the change and had to redeploy on the script. It returned blank. Had to redeploy again and I was able to see the screen.

**Comment by enuchi** [comment]
Are you both running web apps? I see you're using react router dom which might be incompatible with how Google wants you to use browser history in web apps: https://developers.google.com/apps-script/guides/web#web_apps_and_browser_history

**Comment by etaytch** [comment]
I'm experiencing the same.
Started to happen only when I added redux to the code.
@enuchi I do use react router dom, but it never happened before introducing redux..

Usually running `npm run deploy` before `npm run start` solves this..
But this can happen on almost every execution of `npm run start`...

**Comment by mhatvan** [comment]
I also encountered this right now, as a new user with a freshly cloned project. I tried to figure out how the "live reload on save" works, but didn't get far.

`npm run deploy` -> all three demo iframes are working
`npm run start` -> all three demo iframes are blank

**Comment by enuchi** [comment]
Note, there have been significant updates to the way local development works, as well as to the packages used. Please try again with a fresh copy and let me know if you are still experiencing these issue with redux and local development.
