### ISSUE TITLE
React hot reload

### ISSUE THREAD

**Issue by alexblack** [enuchi/React-Google-Apps-Script#96]
Hi again, I love that you've got hot reload built in, but I'm seeing on area where I wonder if I'm doing something wrong, or if it could be improved.

When I save a change to a file, the addon does indeed hot reload, however the react app seems to lose most of its state.  Sometimes this is fine, but other times it really slows down development requiring me to re-create the current state (eg use my addon to do a bunch of stuff) to get back to where I was before the reload.

I believe `react-hot-loader` and react fast refresh https://reactnative.dev/docs/fast-refresh are meant to solve this, but I hit different issues with each and couldn't get them working as expected with the addon.

Have you explored this at all? Thanks!

Alex

**Comment by enuchi** [comment]
Hey again,

Glad you've been interested in this project. Yes would love to have support for hot reloading. If you're able to help get it into this project I'd really appreciate it. I honestly don't know if it's a simple fix or if it would involve rewriting a lot of the project. When I started writing the local development piece of this project, fast-refresh or whatever it's called now was pretty new (still is kind of new), so I went with the older approach with Webpack Dev Server which just refreshes the app -- and that was hard enough! Here's some background on how it works right now:

- [GAS-client](https://github.com/enuchi/gas-client): This is basically a wrapper of `google.script.run` that makes it easier to work with, but in development it proxies calls to the Google Apps Script environment through Google-Apps-Script-Webpack-Dev-Server
- [Google-Apps-Script-Webpack-Dev-Server](https://github.com/enuchi/Google-Apps-Script-Webpack-Dev-Server): This is a fork of Webpack Dev Server, which is what provides the simple version of hot reloading, but listens for requests from gas-client and relays them to the Google Apps Script environment, as well as relays responses back to the development environment.
- React-Google-Apps-Script: This is the sample repo that has all the pieces in place

All these together allow not just hot reloading of the app, but also allows calls to the GAS server from the development environment, so you're not just working with UI.

I'd start with https://github.com/pmmmwh/react-refresh-webpack-plugin. To get it working you might need to update Google-Apps-Script-Webpack-Dev-Server, or this repo, or both.

Hope this is helpful,
Elisha

**Comment by alexblack** [comment]
Hi Elisha, thanks for the info.  I will see if I can give it another shot at some point, I put a fair amount of time in trying to get that working with no luck.

**Comment by enuchi** [comment]
Hey Alex, think I actually have this working with the react-refresh. I actually ripped out Google-Apps-Script-Webpack-Dev-Server altogether, and it's faster and saves state I think. Will update in a bit with how to...

**Comment by enuchi** [comment]
Something like this. When saving, it makes the changes without refreshing the page, and notice the input state is not reset.

![Jun-01-2021 01-44-28](https://user-images.githubusercontent.com/31550519/120272483-2d32c500-c27b-11eb-9dc7-3856bbd4589b.gif)

**Comment by enuchi** [comment]
See https://github.com/enuchi/React-Google-Apps-Script/pull/98

**Comment by alexblack** [comment]
That looks amazing!  I will check it out. Thanks for digging into this.  

I think `/ don't externalize react during development due to issue with react-refresh` might be the issue (or one of the issues I hit), but I didn't know enough about it at the time to even begin to try to solve it.

**Comment by enuchi** [comment]
Yeah, that was definitely a big piece of the puzzle, among other things.

**Comment by alexblack** [comment]
I'm trying out this now.  After implementing the changes, I hit this issue:

https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/343

So I then switched to version `0.5.0-beta.9` of `@pmmmwh/react-refresh-webpack-plugin`, and got past that issue.

Now, when I save changes, I see the app being recompiled (in the Chrome javascript console), but I don't see my changes reflected in the addon. I'm going to double check my work and see if I missed anything.

**Comment by alexblack** [comment]
> So I then switched to version `0.5.0-beta.9` of `@pmmmwh/react-refresh-webpack-plugin`, and got past that issue.

Ah my mistake, thats what you used.  Ignore that :)

**Comment by alexblack** [comment]
Ok I found a mistake or two I made merging those changes in (due to my previous attempts to get this working).  It looks like its working great now, this is a huge improvement. nice work!

**Comment by enuchi** [comment]
Okay glad to hear! Doing this helped me really improve the project.

**Comment by enuchi** [comment]
With #98 support for hot reloading is now included in this project.
