### ISSUE TITLE
Google Apps Script with Typescript

### ISSUE THREAD

**Issue by alexblack** [enuchi/React-Google-Apps-Script#99]
Hi, I see this comment in the readme:

> The server code will need:
> - an entrypoint, usually a file named `index.js`, that loads the app.
> - the entry point will need to declare any public functions by attaching them to the "`global`" object, like this:
>   ```javascript
>   global.onOpen = someFunction;
>   ```
> 

I'm now trying to convert my server/*.js files to typescript, and it seems to work except for index.js, which now fails to compile:

```
ERROR in /src/server/index.ts
    ./src/server/index.ts 29:7-21
    [tsl] ERROR in /src/server/index.ts(29,8)
          TS2339: Property 'myFunctionName' does not exist on type 'Global & typeof globalThis'.
```

Do you have any ideas how to solve this?  Or, can you tell me a bit more about whats going on here, eg is there another way I can achieve whats being done here, exposing the public functions via global?

**Comment by alexblack** [comment]
Also, I've attempted to typescript-ify the calling code in our addon like this:

```
interface ServerTypes {
  serverFunctions: {
    myFunction1: (param: string) => Promise<void>;
    ...
  }
}

const server: ServerTyped = new Server({
  // this is necessary for local development but will be ignored in production
  allowedDevelopmentDomains: (origin: string) =>
    /https:\/\/.*\.googleusercontent\.com$/.test(origin),
  parentTargetOrigin: '*',
});

export default server;
```  

Then later when we import we get type safety:

```
const { serverFunctions } = server;
await serverFunctions.myFunction1('foo');
```

But its very repetitive... each function:
1. Must be first written (no getting around this one :)
2. Then exposed by attaching to `global`
3. Then I write a signature for it on `ServerTyped` 

I'd love to find a way to reduce the boilerplate here.

**Comment by enuchi** [comment]
@guilhermetod did some really great work on this over on [gas-client](https://github.com/enuchi/gas-client) last year but I have not had time to close it out. Have added some tests to that repo but have not merged in anything yet, although it's very close. I have that work on a branch here: https://github.com/enuchi/gas-client/tree/feature/typescript-support

Check out the typescript section in the readme on that page and see if you can get working. I just updated based on the changes to parentTargetOrigin to work with the hot reloading.

**Comment by alexblack** [comment]
Amazing, thanks for sharing that, I will take a look.  In the meantime I made some progress on some improvements on my end, where I used a Promisfy type to create the async version of the Server type for the client, which looks similar to one part of that branch's changes.

**Comment by guilhermetod** [comment]
Hey @enuchi I'm sorry I stopped in the middle of that PR. I was in a hurry with a project and recently got into a new job so I didn't have it the attention needed. I'll see if I can finish the work there by Sunday.

Apart from the annotations you left on the PR, do you need any other help so that we can finish and merge that?

@alexblack in the meantime, I [got my fork published to npm](https://www.npmjs.com/package/@guilhermetod/gas-client). I'll probably archieve that later when we merge it on the original package, but you can use it to feel a gap momentarily.

**Comment by alexblack** [comment]
Great stuff, thanks @guilhermetod .

@enuchi I think the real issue I'm facing right now is that it seems like GAS requires us to attach each function very literally like this:

`global.onOpen = onOpen`

Which is not the end of the world but its repetitive and easy to forget.  I tried other techniques to do this dynamically but it doesn't seem to work, I suspect GAS is naively parsing the file looking for `global.xyz=abc` patterns.

Did you find a solution to this @guilhermetod ?

**Comment by kdar** [comment]
@alexblack I haven't tried this but it seems this sort of thing screams for code generation. In the build, you go through the files and get all the public functions in the module, and generate a file that has the `global.xyz=abc` pattern before uploading.

**Comment by alexblack** [comment]
@kdar that sounds like a great idea, have you seen a good way to do that?

**Comment by enuchi** [comment]
Hey @alexblack, so using `global.myFunction = myFunction` is not actually a GAS requirement but rather the way the [gas-webpack-plugin](https://github.com/fossamagna/gas-webpack-plugin) is able to assign functions to the GAS global scope. That plugin is what I've been using in this project to allow bundling modules for GAS.

I have not experimented with it but I see there is a new configuration called `autoGlobalExportsFiles` which looks like it may auto-generate the global file for you: https://github.com/fossamagna/gas-webpack-plugin#geranate-global-assignment-expressions-from-exports

I'd see if that configuration can do exactly what you and @kdar are talking about.

**Comment by alexblack** [comment]
Thanks again @enuchi , that looks like exactly what I'm looking for.  I seem to have hit an issue with it, that I haven't been able to resolve yet: https://github.com/fossamagna/gas-webpack-plugin/issues/561

**Comment by enuchi** [comment]
Thanks @guilhermetod and no problem at all. I also dropped the ball on that one. I've updated the typescript branch with your work on it and opened a new PR at https://github.com/enuchi/gas-client/pull/19. Think I addressed all the comments but I'll tag you there and continue the conversation.

**Comment by enuchi** [comment]
@alexblack sorry you didn't have luck. I tried it myself and had the same two problems you did so hopefully you get a response to the issues you opened.

**Comment by guilhermetod** [comment]
@alexblack @kdar I honestly figured that it's easier to bundle GAS code usign rollup instead of Webpack. You can build your code like an npm module and just have rollup putting everything flat out on a file. This is an example config based on what I'm using, but with some limitations cleaned up:

```js
import multiEntry from '@rollup/plugin-multi-entry';
import nodeResolve from '@rollup/plugin-node-resolve';
import typescript from '@rollup/plugin-typescript';
import cleanup from 'rollup-plugin-cleanup';

import { stripExports } from './tools/plugins/rollup-plugin-strip-exports';

export default {
  input: {
    include: [
      'src/server/api/**/*.ts',
      'src/server/triggers/**/*.ts',
    ],
    exclude: ['**/*.d.ts'],
  },
  plugins: [
    typescript({
      rootDir: 'src', // @Watch https://github.com/rollup/plugins/issues/287
      tsconfig: 'tsconfig.server.json',
    }),
    nodeResolve(),
    multiEntry(),
    stripExports(),
    cleanup({
      comments: 'none',
      extensions: ['js', 'ts'],
    }),
  ],
  output: { file: 'dist/server/bundle.js' },
};
```

Note that you'll also need the strip exports plugin, so that there is no export statement left on the bundle file.

I started working on an [actual plugin](guilhermetod/rollup-plugin-strip-final-exports) to do this using real ESTree tools. It's actually 100% functional as far as I can tell but I hanged this on for a bit while I finish another project that I'll use in the build. I'll release it when I finish the other project and add some tests. While it's not out, I'm using this and it's been doing the job:

```js
export const stripExports = () => ({
  renderChunk: (sourceCode) => ({
    code: sourceCode.replace(/^export .*/gm, ''),
    map: null,
  }),
});
```

**Comment by guilhermetod** [comment]
Hey everyone, an update here: I just published [`rollup-plugin-strip-final-exports`](https://www.npmjs.com/package/rollup-plugin-strip-final-exports). I've been using rollup to create my bundles and it's been working really nicely, so in case anyone is doing the same, you can now use this plugin in your projects and write your code with `import/export` statements.

Feel free to ask me for help if anyone has any trouble.
